// Generate comprehensive extra words dictionary
// This script creates full word entries with Chinese, IPA, POS, example sentences, and synonyms
// for ALL words found in CET sentences and synonyms that aren't in the CET list

const fs = require('fs');
const path = require('path');

const cetWords = JSON.parse(fs.readFileSync(path.join(__dirname, '../src/data/words.json'), 'utf-8'));
const missingWords = JSON.parse(fs.readFileSync(path.join(__dirname, 'all_missing_words.json'), 'utf-8'));

// Build CET set for dedup
const cetSet = new Set(cetWords.map(w => w.word.toLowerCase()));

// Comprehensive English-Chinese dictionary for common English words
// This covers all 2564 words extracted from CET sentences and synonyms
const DICT = {
  "abroad": { zh: "在国外", ipa: "/əˈbrɔːd/", pos: "adv.", ex: "She studied abroad for two years.", syn: ["overseas", "internationally"] },
  "abrupt": { zh: "突然的", ipa: "/əˈbrʌpt/", pos: "adj.", ex: "The meeting came to an abrupt end.", syn: ["sudden", "unexpected"] },
  "absence": { zh: "缺席；缺乏", ipa: "/ˈæbsəns/", pos: "n.", ex: "His absence was noticed by everyone.", syn: ["lack", "void"] },
  "absent": { zh: "缺席的", ipa: "/ˈæbsənt/", pos: "adj.", ex: "He was absent from class today.", syn: ["missing", "away"] },
  "abuse": { zh: "滥用；虐待", ipa: "/əˈbjuːz/", pos: "v./n.", ex: "They should not abuse their power.", syn: ["misuse", "mistreat"] },
  "academic": { zh: "学术的", ipa: "/ˌækəˈdemɪk/", pos: "adj.", ex: "She has an excellent academic record.", syn: ["scholarly", "educational"] },
  "accept": { zh: "接受", ipa: "/əkˈsept/", pos: "v.", ex: "Please accept my sincere apology.", syn: ["receive", "acknowledge"] },
  "accepted": { zh: "被接受的", ipa: "/əkˈseptɪd/", pos: "adj.", ex: "It is an accepted fact in science.", syn: ["approved", "recognized"] },
  "accessibility": { zh: "可访问性", ipa: "/əkˌsesəˈbɪləti/", pos: "n.", ex: "The website improved its accessibility.", syn: ["availability", "openness"] },
  "accident": { zh: "事故；意外", ipa: "/ˈæksɪdənt/", pos: "n.", ex: "He had a car accident last week.", syn: ["mishap", "incident"] },
  "acclimate": { zh: "适应", ipa: "/ˈæklɪmeɪt/", pos: "v.", ex: "It takes time to acclimate to a new city.", syn: ["adapt", "adjust"] },
  "accord": { zh: "协议；一致", ipa: "/əˈkɔːrd/", pos: "n.", ex: "The two sides reached an accord.", syn: ["agreement", "treaty"] },
  "achievements": { zh: "成就", ipa: "/əˈtʃiːvmənts/", pos: "n.", ex: "Her achievements in science are remarkable.", syn: ["accomplishments", "successes"] },
  "acknowledgment": { zh: "承认；确认", ipa: "/əkˈnɒlɪdʒmənt/", pos: "n.", ex: "He nodded in acknowledgment of her help.", syn: ["recognition", "acceptance"] },
  "act": { zh: "行动；表演", ipa: "/ækt/", pos: "v./n.", ex: "We must act quickly to solve this problem.", syn: ["perform", "deed"] },
  "action": { zh: "行动", ipa: "/ˈækʃən/", pos: "n.", ex: "The government took immediate action.", syn: ["activity", "deed"] },
  "actions": { zh: "行动（复数）", ipa: "/ˈækʃənz/", pos: "n.", ex: "His actions spoke louder than words.", syn: ["deeds", "acts"] },
  "active": { zh: "积极的；活跃的", ipa: "/ˈæktɪv/", pos: "adj.", ex: "She leads a very active lifestyle.", syn: ["energetic", "dynamic"] },
  "activities": { zh: "活动", ipa: "/ækˈtɪvətiz/", pos: "n.", ex: "The school offers many after-class activities.", syn: ["events", "pursuits"] },
  "acts": { zh: "行为", ipa: "/ækts/", pos: "n.", ex: "Random acts of kindness can brighten a day.", syn: ["deeds", "actions"] },
  "actuality": { zh: "实际情况", ipa: "/ˌæktʃuˈæləti/", pos: "n.", ex: "In actuality, the plan was never approved.", syn: ["reality", "truth"] },
  "addition": { zh: "添加；增加", ipa: "/əˈdɪʃən/", pos: "n.", ex: "In addition to English, she speaks French.", syn: ["supplement", "extra"] },
  "address": { zh: "地址；演讲；处理", ipa: "/əˈdres/", pos: "n./v.", ex: "We need to address this issue immediately.", syn: ["tackle", "handle"] },
  "addressed": { zh: "处理了", ipa: "/əˈdrest/", pos: "v.", ex: "The teacher addressed the students' concerns.", syn: ["handled", "dealt with"] },
  "adherence": { zh: "遵守", ipa: "/ədˈhɪərəns/", pos: "n.", ex: "Strict adherence to the rules is required.", syn: ["compliance", "obedience"] },
  "administrator": { zh: "管理员", ipa: "/ədˈmɪnɪstreɪtər/", pos: "n.", ex: "The administrator manages the school budget.", syn: ["manager", "director"] },
  "admission": { zh: "入场；承认", ipa: "/ədˈmɪʃən/", pos: "n.", ex: "Admission to the museum is free on Sundays.", syn: ["entry", "access"] },
  "admit": { zh: "承认；允许进入", ipa: "/ədˈmɪt/", pos: "v.", ex: "He had to admit he was wrong.", syn: ["confess", "acknowledge"] },
  "adopt": { zh: "采纳；收养", ipa: "/əˈdɒpt/", pos: "v.", ex: "They decided to adopt a new strategy.", syn: ["embrace", "accept"] },
  "adopted": { zh: "采纳了的", ipa: "/əˈdɒptɪd/", pos: "v.", ex: "The company adopted new policies last year.", syn: ["accepted", "implemented"] },
  "adore": { zh: "崇拜；热爱", ipa: "/əˈdɔːr/", pos: "v.", ex: "The children adore their grandmother.", syn: ["love", "worship"] },
  "adorn": { zh: "装饰", ipa: "/əˈdɔːrn/", pos: "v.", ex: "Flowers adorn the entrance of the building.", syn: ["decorate", "embellish"] },
  "advance": { zh: "前进；进步", ipa: "/ədˈvɑːns/", pos: "v./n.", ex: "Technology continues to advance rapidly.", syn: ["progress", "improve"] },
  "adversary": { zh: "对手", ipa: "/ˈædvərsəri/", pos: "n.", ex: "He respected his adversary in the competition.", syn: ["opponent", "rival"] },
  "adverse": { zh: "不利的", ipa: "/ˈædvɜːrs/", pos: "adj.", ex: "The project faced adverse weather conditions.", syn: ["unfavorable", "harmful"] },
  "advertisement": { zh: "广告", ipa: "/ədˈvɜːrtɪsmənt/", pos: "n.", ex: "I saw an advertisement for the new phone.", syn: ["ad", "commercial"] },
  "advertising": { zh: "广告业", ipa: "/ˈædvərtaɪzɪŋ/", pos: "n.", ex: "She works in advertising and marketing.", syn: ["promotion", "publicity"] },
  "advice": { zh: "建议", ipa: "/ədˈvaɪs/", pos: "n.", ex: "She gave me some useful advice.", syn: ["guidance", "counsel"] },
  "advise": { zh: "建议", ipa: "/ədˈvaɪz/", pos: "v.", ex: "I would advise you to study harder.", syn: ["recommend", "suggest"] },
  "aeronautics": { zh: "航空学", ipa: "/ˌeərəˈnɔːtɪks/", pos: "n.", ex: "She studied aeronautics at university.", syn: ["aviation", "flight science"] },
  "affront": { zh: "侮辱", ipa: "/əˈfrʌnt/", pos: "n./v.", ex: "His remark was an affront to her dignity.", syn: ["insult", "offense"] },
  "africa": { zh: "非洲", ipa: "/ˈæfrɪkə/", pos: "n.", ex: "Africa is the second largest continent.", syn: [] },
  "afternoon": { zh: "下午", ipa: "/ˌɑːftərˈnuːn/", pos: "n.", ex: "We have a meeting this afternoon.", syn: ["midday", "p.m."] },
  "age": { zh: "年龄；时代", ipa: "/eɪdʒ/", pos: "n.", ex: "People of all ages enjoy this park.", syn: ["era", "period"] },
  "aged": { zh: "年老的", ipa: "/eɪdʒd/", pos: "adj.", ex: "The aged building needs renovation.", syn: ["elderly", "old"] },
  "agenda": { zh: "议程", ipa: "/əˈdʒendə/", pos: "n.", ex: "What is on today's agenda?", syn: ["schedule", "plan"] },
  "agree": { zh: "同意", ipa: "/əˈɡriː/", pos: "v.", ex: "I agree with your suggestion.", syn: ["concur", "consent"] },
  "agreed": { zh: "同意了的", ipa: "/əˈɡriːd/", pos: "v.", ex: "They agreed to meet at noon.", syn: ["consented", "accepted"] },
  "agreement": { zh: "协议；同意", ipa: "/əˈɡriːmənt/", pos: "n.", ex: "They signed a trade agreement.", syn: ["contract", "pact"] },
  "ahead": { zh: "在前面", ipa: "/əˈhed/", pos: "adv.", ex: "Go ahead and start without me.", syn: ["forward", "onward"] },
  "aid": { zh: "帮助；援助", ipa: "/eɪd/", pos: "n./v.", ex: "The country received international aid.", syn: ["assistance", "support"] },
  "aim": { zh: "目标；瞄准", ipa: "/eɪm/", pos: "n./v.", ex: "Our aim is to finish the project on time.", syn: ["goal", "target"] },
  "aimed": { zh: "旨在", ipa: "/eɪmd/", pos: "v.", ex: "The program is aimed at young students.", syn: ["targeted", "directed"] },
  "alert": { zh: "警觉的", ipa: "/əˈlɜːrt/", pos: "adj./n.", ex: "Stay alert while driving at night.", syn: ["vigilant", "watchful"] },
  "alleviate": { zh: "减轻", ipa: "/əˈliːvieɪt/", pos: "v.", ex: "Medicine can alleviate the pain.", syn: ["relieve", "ease"] },
  "allocate": { zh: "分配", ipa: "/ˈæləkeɪt/", pos: "v.", ex: "The funds were allocated to education.", syn: ["assign", "distribute"] },
  "allot": { zh: "分配", ipa: "/əˈlɒt/", pos: "v.", ex: "Each student was allotted ten minutes.", syn: ["assign", "allocate"] },
  "alongside": { zh: "在旁边", ipa: "/əˌlɒŋˈsaɪd/", pos: "prep.", ex: "He worked alongside his colleagues.", syn: ["beside", "next to"] },
  "alter": { zh: "改变", ipa: "/ˈɔːltər/", pos: "v.", ex: "We had to alter our plans.", syn: ["change", "modify"] },
  "altitude": { zh: "海拔", ipa: "/ˈæltɪtjuːd/", pos: "n.", ex: "The plane reached a high altitude.", syn: ["elevation", "height"] },
  "amass": { zh: "积累", ipa: "/əˈmæs/", pos: "v.", ex: "He managed to amass a large fortune.", syn: ["accumulate", "gather"] },
  "ambiance": { zh: "氛围", ipa: "/ˈæmbiəns/", pos: "n.", ex: "The restaurant has a lovely ambiance.", syn: ["atmosphere", "mood"] },
  "ambiguity": { zh: "模糊", ipa: "/ˌæmbɪˈɡjuːəti/", pos: "n.", ex: "There is some ambiguity in the contract.", syn: ["uncertainty", "vagueness"] },
  "ambition": { zh: "雄心", ipa: "/æmˈbɪʃən/", pos: "n.", ex: "Her ambition is to become a doctor.", syn: ["aspiration", "goal"] },
  "ambitious": { zh: "有雄心的", ipa: "/æmˈbɪʃəs/", pos: "adj.", ex: "She is ambitious and hardworking.", syn: ["driven", "determined"] },
  "amid": { zh: "在…之中", ipa: "/əˈmɪd/", pos: "prep.", ex: "He remained calm amid the chaos.", syn: ["among", "in the middle of"] },
  "amount": { zh: "数量", ipa: "/əˈmaʊnt/", pos: "n.", ex: "A large amount of money was spent.", syn: ["quantity", "sum"] },
  "ample": { zh: "充足的", ipa: "/ˈæmpəl/", pos: "adj.", ex: "There is ample time to prepare.", syn: ["sufficient", "plentiful"] },
  "amuse": { zh: "使发笑", ipa: "/əˈmjuːz/", pos: "v.", ex: "The clown amused the children.", syn: ["entertain", "delight"] },
  "ancient": { zh: "古代的", ipa: "/ˈeɪnʃənt/", pos: "adj.", ex: "We visited the ancient ruins in Rome.", syn: ["old", "antique"] },
  "anger": { zh: "愤怒", ipa: "/ˈæŋɡər/", pos: "n.", ex: "He tried to control his anger.", syn: ["rage", "fury"] },
  "angle": { zh: "角度", ipa: "/ˈæŋɡəl/", pos: "n.", ex: "Look at the problem from a different angle.", syn: ["perspective", "viewpoint"] },
  "announce": { zh: "宣布", ipa: "/əˈnaʊns/", pos: "v.", ex: "They will announce the results tomorrow.", syn: ["declare", "proclaim"] },
  "announced": { zh: "宣布了", ipa: "/əˈnaʊnst/", pos: "v.", ex: "The company announced a new product.", syn: ["declared", "revealed"] },
  "annual": { zh: "年度的", ipa: "/ˈænjuəl/", pos: "adj.", ex: "The annual conference is held in May.", syn: ["yearly", "per annum"] },
  "anxiety": { zh: "焦虑", ipa: "/æŋˈzaɪəti/", pos: "n.", ex: "She suffered from anxiety before exams.", syn: ["worry", "nervousness"] },
  "anxious": { zh: "焦虑的", ipa: "/ˈæŋkʃəs/", pos: "adj.", ex: "He was anxious about the interview.", syn: ["worried", "nervous"] },
  "apart": { zh: "分开", ipa: "/əˈpɑːrt/", pos: "adv.", ex: "They live far apart from each other.", syn: ["separately", "away"] },
  "appeal": { zh: "呼吁；吸引力", ipa: "/əˈpiːl/", pos: "n./v.", ex: "The idea has wide appeal.", syn: ["attract", "request"] },
  "appetite": { zh: "食欲", ipa: "/ˈæpɪtaɪt/", pos: "n.", ex: "Exercise increases your appetite.", syn: ["hunger", "craving"] },
  "appliance": { zh: "家用电器", ipa: "/əˈplaɪəns/", pos: "n.", ex: "The kitchen has modern appliances.", syn: ["device", "gadget"] },
  "application": { zh: "申请；应用", ipa: "/ˌæplɪˈkeɪʃən/", pos: "n.", ex: "She submitted her college application.", syn: ["request", "usage"] },
  "applied": { zh: "应用的", ipa: "/əˈplaɪd/", pos: "v.", ex: "He applied for the job online.", syn: ["used", "implemented"] },
  "apply": { zh: "申请；应用", ipa: "/əˈplaɪ/", pos: "v.", ex: "You can apply for a scholarship.", syn: ["request", "utilize"] },
  "appoint": { zh: "任命", ipa: "/əˈpɔɪnt/", pos: "v.", ex: "They appointed her as the new manager.", syn: ["designate", "assign"] },
  "appointed": { zh: "被任命的", ipa: "/əˈpɔɪntɪd/", pos: "v.", ex: "He was appointed to lead the team.", syn: ["designated", "assigned"] },
  "appreciate": { zh: "感激；欣赏", ipa: "/əˈpriːʃieɪt/", pos: "v.", ex: "I appreciate your help very much.", syn: ["value", "cherish"] },
  "appreciation": { zh: "感激", ipa: "/əˌpriːʃiˈeɪʃən/", pos: "n.", ex: "She expressed her appreciation for the gift.", syn: ["gratitude", "thanks"] },
  "approach": { zh: "方法；接近", ipa: "/əˈprəʊtʃ/", pos: "n./v.", ex: "We need a new approach to this problem.", syn: ["method", "strategy"] },
  "appropriate": { zh: "合适的", ipa: "/əˈprəʊpriət/", pos: "adj.", ex: "Wear appropriate clothing for the event.", syn: ["suitable", "proper"] },
  "approval": { zh: "批准", ipa: "/əˈpruːvəl/", pos: "n.", ex: "The plan needs the director's approval.", syn: ["consent", "permission"] },
  "approve": { zh: "批准", ipa: "/əˈpruːv/", pos: "v.", ex: "The board will approve the budget.", syn: ["endorse", "sanction"] },
  "approximately": { zh: "大约", ipa: "/əˈprɒksɪmətli/", pos: "adv.", ex: "The trip takes approximately two hours.", syn: ["roughly", "about"] },
  "area": { zh: "区域", ipa: "/ˈeəriə/", pos: "n.", ex: "This area is known for its wildlife.", syn: ["region", "zone"] },
  "argue": { zh: "争论", ipa: "/ˈɑːrɡjuː/", pos: "v.", ex: "They argue about politics all the time.", syn: ["debate", "dispute"] },
  "argued": { zh: "争论了", ipa: "/ˈɑːrɡjuːd/", pos: "v.", ex: "She argued that the policy was unfair.", syn: ["debated", "contended"] },
  "argument": { zh: "争论；论点", ipa: "/ˈɑːrɡjumənt/", pos: "n.", ex: "They had an argument about money.", syn: ["dispute", "debate"] },
  "arise": { zh: "出现", ipa: "/əˈraɪz/", pos: "v.", ex: "Problems may arise during the project.", syn: ["emerge", "occur"] },
  "arose": { zh: "出现了", ipa: "/əˈrəʊz/", pos: "v.", ex: "A new opportunity arose unexpectedly.", syn: ["emerged", "appeared"] },
  "arrangement": { zh: "安排", ipa: "/əˈreɪndʒmənt/", pos: "n.", ex: "We made arrangements for the trip.", syn: ["plan", "setup"] },
  "arrest": { zh: "逮捕", ipa: "/əˈrest/", pos: "v./n.", ex: "The police made an arrest this morning.", syn: ["capture", "detain"] },
  "arrival": { zh: "到达", ipa: "/əˈraɪvəl/", pos: "n.", ex: "We are awaiting the arrival of the guests.", syn: ["coming", "appearance"] },
  "arrive": { zh: "到达", ipa: "/əˈraɪv/", pos: "v.", ex: "The train will arrive at three o'clock.", syn: ["come", "reach"] },
  "arrived": { zh: "到达了", ipa: "/əˈraɪvd/", pos: "v.", ex: "She arrived early for the meeting.", syn: ["came", "reached"] },
  "article": { zh: "文章；物品", ipa: "/ˈɑːrtɪkəl/", pos: "n.", ex: "He wrote an article about climate change.", syn: ["essay", "piece"] },
  "aspect": { zh: "方面", ipa: "/ˈæspekt/", pos: "n.", ex: "We need to consider every aspect of the plan.", syn: ["feature", "facet"] },
  "assemble": { zh: "组装；集合", ipa: "/əˈsembəl/", pos: "v.", ex: "The team assembled in the conference room.", syn: ["gather", "collect"] },
  "assert": { zh: "断言", ipa: "/əˈsɜːrt/", pos: "v.", ex: "He asserted that the data was accurate.", syn: ["declare", "claim"] },
  "assess": { zh: "评估", ipa: "/əˈses/", pos: "v.", ex: "We need to assess the damage carefully.", syn: ["evaluate", "judge"] },
  "assessment": { zh: "评估", ipa: "/əˈsesmənt/", pos: "n.", ex: "The assessment showed positive results.", syn: ["evaluation", "appraisal"] },
  "asset": { zh: "资产", ipa: "/ˈæset/", pos: "n.", ex: "Her experience is a valuable asset.", syn: ["resource", "advantage"] },
  "assign": { zh: "分配", ipa: "/əˈsaɪn/", pos: "v.", ex: "The teacher will assign homework today.", syn: ["allocate", "designate"] },
  "assigned": { zh: "分配了", ipa: "/əˈsaɪnd/", pos: "v.", ex: "Each student was assigned a partner.", syn: ["allocated", "given"] },
  "assist": { zh: "帮助", ipa: "/əˈsɪst/", pos: "v.", ex: "Can I assist you with your luggage?", syn: ["help", "support"] },
  "assistance": { zh: "帮助", ipa: "/əˈsɪstəns/", pos: "n.", ex: "Thank you for your assistance.", syn: ["help", "aid"] },
  "associate": { zh: "联系；同事", ipa: "/əˈsəʊʃieɪt/", pos: "v./n.", ex: "People associate sunshine with happiness.", syn: ["connect", "link"] },
  "associated": { zh: "相关的", ipa: "/əˈsəʊʃieɪtɪd/", pos: "adj.", ex: "Health risks associated with smoking are severe.", syn: ["related", "connected"] },
  "assume": { zh: "假设", ipa: "/əˈsjuːm/", pos: "v.", ex: "I assume you have read the report.", syn: ["presume", "suppose"] },
  "assurance": { zh: "保证", ipa: "/əˈʃʊərəns/", pos: "n.", ex: "He gave me his assurance that it would be done.", syn: ["guarantee", "promise"] },
  "assure": { zh: "保证", ipa: "/əˈʃʊər/", pos: "v.", ex: "I assure you that everything will be fine.", syn: ["guarantee", "promise"] },
  "athlete": { zh: "运动员", ipa: "/ˈæθliːt/", pos: "n.", ex: "The athlete won a gold medal.", syn: ["sportsman", "competitor"] },
  "atmosphere": { zh: "大气；氛围", ipa: "/ˈætməsfɪər/", pos: "n.", ex: "The atmosphere in the room was tense.", syn: ["ambiance", "environment"] },
  "attach": { zh: "附上", ipa: "/əˈtætʃ/", pos: "v.", ex: "Please attach your resume to the email.", syn: ["fasten", "connect"] },
  "attached": { zh: "附上的", ipa: "/əˈtætʃt/", pos: "adj.", ex: "The file is attached to this email.", syn: ["connected", "fastened"] },
  "attempt": { zh: "尝试", ipa: "/əˈtempt/", pos: "v./n.", ex: "He made an attempt to climb the mountain.", syn: ["try", "endeavor"] },
  "attempted": { zh: "试图了", ipa: "/əˈtemptɪd/", pos: "v.", ex: "She attempted to solve the puzzle.", syn: ["tried", "endeavored"] },
  "attend": { zh: "参加", ipa: "/əˈtend/", pos: "v.", ex: "Will you attend the conference tomorrow?", syn: ["join", "participate"] },
  "attendance": { zh: "出席", ipa: "/əˈtendəns/", pos: "n.", ex: "Attendance at the meeting is mandatory.", syn: ["presence", "turnout"] },
  "attention": { zh: "注意力", ipa: "/əˈtenʃən/", pos: "n.", ex: "Pay attention to the teacher.", syn: ["focus", "concentration"] },
  "attitude": { zh: "态度", ipa: "/ˈætɪtjuːd/", pos: "n.", ex: "A positive attitude helps in difficult times.", syn: ["mindset", "outlook"] },
  "attract": { zh: "吸引", ipa: "/əˈtrækt/", pos: "v.", ex: "The park attracts millions of visitors.", syn: ["draw", "lure"] },
  "attractive": { zh: "有吸引力的", ipa: "/əˈtræktɪv/", pos: "adj.", ex: "The offer was very attractive.", syn: ["appealing", "charming"] },
  "audience": { zh: "观众", ipa: "/ˈɔːdiəns/", pos: "n.", ex: "The audience applauded loudly.", syn: ["spectators", "viewers"] },
  "authentic": { zh: "真实的", ipa: "/ɔːˈθentɪk/", pos: "adj.", ex: "The painting is an authentic masterpiece.", syn: ["genuine", "real"] },
  "authority": { zh: "权威；当局", ipa: "/ɔːˈθɒrəti/", pos: "n.", ex: "The local authority approved the project.", syn: ["power", "jurisdiction"] },
  "automatically": { zh: "自动地", ipa: "/ˌɔːtəˈmætɪkli/", pos: "adv.", ex: "The door opens automatically.", syn: ["mechanically", "spontaneously"] },
  "available": { zh: "可用的", ipa: "/əˈveɪləbəl/", pos: "adj.", ex: "The room is available for booking.", syn: ["accessible", "obtainable"] },
  "average": { zh: "平均的", ipa: "/ˈævərɪdʒ/", pos: "adj./n.", ex: "The average temperature is twenty degrees.", syn: ["mean", "typical"] },
  "avoid": { zh: "避免", ipa: "/əˈvɔɪd/", pos: "v.", ex: "Try to avoid making the same mistake.", syn: ["evade", "prevent"] },
  "award": { zh: "奖励", ipa: "/əˈwɔːrd/", pos: "n./v.", ex: "She received an award for her research.", syn: ["prize", "honor"] },
  "awarded": { zh: "被授予", ipa: "/əˈwɔːrdɪd/", pos: "v.", ex: "He was awarded the Nobel Prize.", syn: ["granted", "given"] },
  "aware": { zh: "意识到的", ipa: "/əˈweər/", pos: "adj.", ex: "Are you aware of the risks?", syn: ["conscious", "mindful"] },
  "awareness": { zh: "意识", ipa: "/əˈweərnəs/", pos: "n.", ex: "There is growing awareness of the issue.", syn: ["consciousness", "knowledge"] },
  "bachelor": { zh: "学士；单身汉", ipa: "/ˈbætʃələr/", pos: "n.", ex: "He earned a bachelor's degree in engineering.", syn: ["graduate", "single man"] },
  "background": { zh: "背景", ipa: "/ˈbækɡraʊnd/", pos: "n.", ex: "She has a background in computer science.", syn: ["history", "context"] },
  "badly": { zh: "严重地", ipa: "/ˈbædli/", pos: "adv.", ex: "The house was badly damaged.", syn: ["severely", "poorly"] },
  "balance": { zh: "平衡", ipa: "/ˈbæləns/", pos: "n./v.", ex: "You need to balance work and life.", syn: ["equilibrium", "stability"] },
  "ban": { zh: "禁止", ipa: "/bæn/", pos: "v./n.", ex: "The government plans to ban smoking.", syn: ["prohibit", "forbid"] },
  "band": { zh: "乐队；带", ipa: "/bænd/", pos: "n.", ex: "The band performed at the concert.", syn: ["group", "ensemble"] },
  "bank": { zh: "银行", ipa: "/bæŋk/", pos: "n.", ex: "She went to the bank to deposit money.", syn: ["financial institution"] },
  "barely": { zh: "几乎不", ipa: "/ˈbeərli/", pos: "adv.", ex: "She could barely hear the music.", syn: ["hardly", "scarcely"] },
  "bargain": { zh: "讨价还价；便宜货", ipa: "/ˈbɑːrɡən/", pos: "n./v.", ex: "The coat was a real bargain.", syn: ["deal", "discount"] },
  "barrier": { zh: "障碍", ipa: "/ˈbæriər/", pos: "n.", ex: "Language can be a barrier to communication.", syn: ["obstacle", "hurdle"] },
  "base": { zh: "基础", ipa: "/beɪs/", pos: "n./v.", ex: "The theory is based on solid evidence.", syn: ["foundation", "basis"] },
  "based": { zh: "基于", ipa: "/beɪst/", pos: "adj.", ex: "The film is based on a true story.", syn: ["founded", "grounded"] },
  "basic": { zh: "基本的", ipa: "/ˈbeɪsɪk/", pos: "adj.", ex: "You need to learn the basic rules first.", syn: ["fundamental", "elementary"] },
  "basis": { zh: "基础", ipa: "/ˈbeɪsɪs/", pos: "n.", ex: "We meet on a regular basis.", syn: ["foundation", "grounds"] },
  "battle": { zh: "战斗", ipa: "/ˈbætəl/", pos: "n./v.", ex: "They fought a long battle against disease.", syn: ["fight", "combat"] },
  "bear": { zh: "承受；忍受", ipa: "/beər/", pos: "v.", ex: "She could not bear the pain any longer.", syn: ["endure", "tolerate"] },
  "beat": { zh: "打败；心跳", ipa: "/biːt/", pos: "v.", ex: "Our team beat them in the final game.", syn: ["defeat", "overcome"] },
  "beauty": { zh: "美丽", ipa: "/ˈbjuːti/", pos: "n.", ex: "The beauty of the sunset was breathtaking.", syn: ["attractiveness", "elegance"] },
  "behalf": { zh: "代表", ipa: "/bɪˈhɑːf/", pos: "n.", ex: "He spoke on behalf of the team.", syn: ["interest", "support"] },
  "behave": { zh: "表现", ipa: "/bɪˈheɪv/", pos: "v.", ex: "Children should behave well in public.", syn: ["act", "conduct oneself"] },
  "behavior": { zh: "行为", ipa: "/bɪˈheɪvjər/", pos: "n.", ex: "His behavior was unacceptable.", syn: ["conduct", "manner"] },
  "belong": { zh: "属于", ipa: "/bɪˈlɒŋ/", pos: "v.", ex: "This book belongs to the library.", syn: ["pertain", "be owned by"] },
  "belongs": { zh: "属于", ipa: "/bɪˈlɒŋz/", pos: "v.", ex: "The decision belongs to the committee.", syn: ["pertains", "relates"] },
  "beneath": { zh: "在…下面", ipa: "/bɪˈniːθ/", pos: "prep.", ex: "The treasure was buried beneath the tree.", syn: ["under", "below"] },
  "benefit": { zh: "好处；受益", ipa: "/ˈbenɪfɪt/", pos: "n./v.", ex: "Exercise has many health benefits.", syn: ["advantage", "profit"] },
  "benefits": { zh: "好处", ipa: "/ˈbenɪfɪts/", pos: "n.", ex: "The job offers excellent benefits.", syn: ["advantages", "perks"] },
  "bias": { zh: "偏见", ipa: "/ˈbaɪəs/", pos: "n.", ex: "The report showed no bias.", syn: ["prejudice", "partiality"] },
  "bid": { zh: "出价；努力", ipa: "/bɪd/", pos: "n./v.", ex: "He made a bid for the contract.", syn: ["offer", "attempt"] },
  "billion": { zh: "十亿", ipa: "/ˈbɪljən/", pos: "n.", ex: "The company is worth several billion dollars.", syn: ["thousand million"] },
  "bind": { zh: "绑；约束", ipa: "/baɪnd/", pos: "v.", ex: "The contract will bind both parties.", syn: ["tie", "fasten"] },
  "bit": { zh: "一点", ipa: "/bɪt/", pos: "n.", ex: "Wait a bit before you decide.", syn: ["piece", "fragment"] },
  "bite": { zh: "咬", ipa: "/baɪt/", pos: "v./n.", ex: "Be careful, the dog might bite.", syn: ["chomp", "nip"] },
  "bitter": { zh: "苦的", ipa: "/ˈbɪtər/", pos: "adj.", ex: "The medicine has a bitter taste.", syn: ["harsh", "acrid"] },
  "blame": { zh: "责备", ipa: "/bleɪm/", pos: "v./n.", ex: "Don't blame others for your mistakes.", syn: ["accuse", "fault"] },
  "blank": { zh: "空白的", ipa: "/blæŋk/", pos: "adj.", ex: "Please fill in the blank spaces.", syn: ["empty", "void"] },
  "blast": { zh: "爆炸", ipa: "/blɑːst/", pos: "n./v.", ex: "The blast shattered all the windows.", syn: ["explosion", "burst"] },
  "blaze": { zh: "火焰", ipa: "/bleɪz/", pos: "n./v.", ex: "The firefighters fought the blaze all night.", syn: ["fire", "flame"] },
  "blend": { zh: "混合", ipa: "/blend/", pos: "v./n.", ex: "Blend the ingredients until smooth.", syn: ["mix", "combine"] },
  "bless": { zh: "祝福", ipa: "/bles/", pos: "v.", ex: "May God bless you and your family.", syn: ["sanctify", "consecrate"] },
  "blind": { zh: "盲的", ipa: "/blaɪnd/", pos: "adj.", ex: "The accident left him blind in one eye.", syn: ["sightless", "unseeing"] },
  "block": { zh: "阻挡；街区", ipa: "/blɒk/", pos: "v./n.", ex: "A fallen tree blocked the road.", syn: ["obstruct", "barrier"] },
  "blow": { zh: "吹；打击", ipa: "/bləʊ/", pos: "v./n.", ex: "The wind began to blow harder.", syn: ["gust", "strike"] },
  "board": { zh: "董事会；木板", ipa: "/bɔːrd/", pos: "n.", ex: "The board approved the new policy.", syn: ["committee", "panel"] },
  "boast": { zh: "吹嘘", ipa: "/bəʊst/", pos: "v.", ex: "He likes to boast about his achievements.", syn: ["brag", "show off"] },
  "bold": { zh: "大胆的", ipa: "/bəʊld/", pos: "adj.", ex: "It was a bold decision to start a new business.", syn: ["brave", "daring"] },
  "bond": { zh: "纽带；债券", ipa: "/bɒnd/", pos: "n.", ex: "The bond between mother and child is strong.", syn: ["connection", "tie"] },
  "bonus": { zh: "奖金", ipa: "/ˈbəʊnəs/", pos: "n.", ex: "Employees received a year-end bonus.", syn: ["reward", "extra"] },
  "boom": { zh: "繁荣；轰鸣", ipa: "/buːm/", pos: "n./v.", ex: "The tech industry experienced a boom.", syn: ["surge", "growth"] },
  "boost": { zh: "提升", ipa: "/buːst/", pos: "v./n.", ex: "The new policy will boost the economy.", syn: ["increase", "enhance"] },
  "border": { zh: "边界", ipa: "/ˈbɔːrdər/", pos: "n.", ex: "They crossed the border into Canada.", syn: ["boundary", "frontier"] },
  "bore": { zh: "使无聊", ipa: "/bɔːr/", pos: "v.", ex: "The long lecture began to bore the students.", syn: ["tire", "weary"] },
  "born": { zh: "出生的", ipa: "/bɔːrn/", pos: "adj.", ex: "She was born in a small town.", syn: ["native", "innate"] },
  "bother": { zh: "打扰", ipa: "/ˈbɒðər/", pos: "v.", ex: "Sorry to bother you so late.", syn: ["disturb", "annoy"] },
  "bottom": { zh: "底部", ipa: "/ˈbɒtəm/", pos: "n.", ex: "The keys fell to the bottom of the bag.", syn: ["base", "foot"] },
  "bound": { zh: "一定的；跳", ipa: "/baʊnd/", pos: "adj./v.", ex: "She is bound to succeed.", syn: ["certain", "destined"] },
  "boundary": { zh: "边界", ipa: "/ˈbaʊndəri/", pos: "n.", ex: "The river forms a natural boundary.", syn: ["border", "limit"] },
  "branch": { zh: "分支；树枝", ipa: "/brɑːntʃ/", pos: "n.", ex: "The company opened a new branch in London.", syn: ["division", "section"] },
  "brand": { zh: "品牌", ipa: "/brænd/", pos: "n.", ex: "This is a well-known brand of shoes.", syn: ["label", "trademark"] },
  "brave": { zh: "勇敢的", ipa: "/breɪv/", pos: "adj.", ex: "The brave firefighter saved the child.", syn: ["courageous", "bold"] },
  "breach": { zh: "违反；破坏", ipa: "/briːtʃ/", pos: "n./v.", ex: "This is a breach of the agreement.", syn: ["violation", "break"] },
  "break": { zh: "打破；休息", ipa: "/breɪk/", pos: "v./n.", ex: "Let's take a short break.", syn: ["pause", "fracture"] },
  "breed": { zh: "品种；繁殖", ipa: "/briːd/", pos: "n./v.", ex: "This breed of dog is very friendly.", syn: ["type", "kind"] },
  "brief": { zh: "简短的", ipa: "/briːf/", pos: "adj.", ex: "He gave a brief summary of the report.", syn: ["short", "concise"] },
  "briefly": { zh: "简短地", ipa: "/ˈbriːfli/", pos: "adv.", ex: "She briefly explained the situation.", syn: ["shortly", "concisely"] },
  "brilliant": { zh: "杰出的", ipa: "/ˈbrɪljənt/", pos: "adj.", ex: "She had a brilliant idea.", syn: ["outstanding", "excellent"] },
  "broad": { zh: "宽广的", ipa: "/brɔːd/", pos: "adj.", ex: "The river is very broad at this point.", syn: ["wide", "extensive"] },
  "broadcast": { zh: "广播", ipa: "/ˈbrɔːdkɑːst/", pos: "v./n.", ex: "The event will be broadcast live on TV.", syn: ["transmit", "air"] },
  "broke": { zh: "破产的", ipa: "/brəʊk/", pos: "adj.", ex: "He went broke after the investment failed.", syn: ["bankrupt", "penniless"] },
  "budget": { zh: "预算", ipa: "/ˈbʌdʒɪt/", pos: "n.", ex: "The project exceeded its budget.", syn: ["funds", "allowance"] },
  "bulk": { zh: "大量", ipa: "/bʌlk/", pos: "n.", ex: "We bought the supplies in bulk.", syn: ["mass", "volume"] },
  "burden": { zh: "负担", ipa: "/ˈbɜːrdən/", pos: "n.", ex: "The tax burden is heavy for small businesses.", syn: ["load", "weight"] },
  "bureau": { zh: "局；办事处", ipa: "/ˈbjʊərəʊ/", pos: "n.", ex: "Contact the travel bureau for information.", syn: ["office", "agency"] },
  "burst": { zh: "爆发", ipa: "/bɜːrst/", pos: "v./n.", ex: "The balloon burst with a loud pop.", syn: ["explode", "rupture"] },
  "bus": { zh: "公共汽车", ipa: "/bʌs/", pos: "n.", ex: "I take the bus to school every day.", syn: ["coach", "shuttle"] },
  "busy": { zh: "忙碌的", ipa: "/ˈbɪzi/", pos: "adj.", ex: "She is always busy with work.", syn: ["occupied", "engaged"] },
  "cabinet": { zh: "内阁；橱柜", ipa: "/ˈkæbɪnɪt/", pos: "n.", ex: "The cabinet held an emergency meeting.", syn: ["cupboard", "council"] },
  "calculate": { zh: "计算", ipa: "/ˈkælkjuleɪt/", pos: "v.", ex: "We need to calculate the total cost.", syn: ["compute", "figure out"] },
  "calm": { zh: "平静的", ipa: "/kɑːm/", pos: "adj.", ex: "Please stay calm during the emergency.", syn: ["peaceful", "serene"] },
  "campaign": { zh: "运动；活动", ipa: "/kæmˈpeɪn/", pos: "n.", ex: "The advertising campaign was very successful.", syn: ["drive", "movement"] },
  "campus": { zh: "校园", ipa: "/ˈkæmpəs/", pos: "n.", ex: "The university campus is very beautiful.", syn: ["grounds", "site"] },
  "candidate": { zh: "候选人", ipa: "/ˈkændɪdeɪt/", pos: "n.", ex: "She is a strong candidate for the position.", syn: ["applicant", "contender"] },
  "capable": { zh: "有能力的", ipa: "/ˈkeɪpəbəl/", pos: "adj.", ex: "She is capable of handling the task.", syn: ["competent", "able"] },
  "capacity": { zh: "容量；能力", ipa: "/kəˈpæsəti/", pos: "n.", ex: "The stadium has a capacity of fifty thousand.", syn: ["ability", "volume"] },
  "capital": { zh: "首都；资本", ipa: "/ˈkæpɪtəl/", pos: "n.", ex: "Beijing is the capital of China.", syn: ["funds", "assets"] },
  "capture": { zh: "捕获", ipa: "/ˈkæptʃər/", pos: "v.", ex: "The photographer captured a stunning image.", syn: ["seize", "catch"] },
  "carbon": { zh: "碳", ipa: "/ˈkɑːrbən/", pos: "n.", ex: "We need to reduce carbon emissions.", syn: ["element"] },
  "career": { zh: "职业", ipa: "/kəˈrɪər/", pos: "n.", ex: "She built a successful career in medicine.", syn: ["profession", "occupation"] },
  "careful": { zh: "小心的", ipa: "/ˈkeəfəl/", pos: "adj.", ex: "Be careful when crossing the street.", syn: ["cautious", "attentive"] },
  "carefully": { zh: "仔细地", ipa: "/ˈkeəfəli/", pos: "adv.", ex: "She carefully read every word.", syn: ["cautiously", "attentively"] },
  "carry": { zh: "携带", ipa: "/ˈkæri/", pos: "v.", ex: "Can you carry this box for me?", syn: ["transport", "bear"] },
  "cast": { zh: "投掷；演员阵容", ipa: "/kɑːst/", pos: "v./n.", ex: "The movie has an excellent cast.", syn: ["throw", "hurl"] },
  "catch": { zh: "抓住", ipa: "/kætʃ/", pos: "v.", ex: "Try to catch the ball.", syn: ["grab", "seize"] },
  "category": { zh: "类别", ipa: "/ˈkætəɡəri/", pos: "n.", ex: "The books are sorted by category.", syn: ["class", "group"] },
  "cause": { zh: "原因；引起", ipa: "/kɔːz/", pos: "n./v.", ex: "Smoking can cause serious health problems.", syn: ["reason", "trigger"] },
  "caused": { zh: "引起了", ipa: "/kɔːzd/", pos: "v.", ex: "The storm caused widespread damage.", syn: ["triggered", "produced"] },
  "caution": { zh: "谨慎", ipa: "/ˈkɔːʃən/", pos: "n.", ex: "Proceed with caution on icy roads.", syn: ["care", "prudence"] },
  "cease": { zh: "停止", ipa: "/siːs/", pos: "v.", ex: "The factory will cease operations next month.", syn: ["stop", "halt"] },
  "celebrate": { zh: "庆祝", ipa: "/ˈselɪbreɪt/", pos: "v.", ex: "We celebrate Chinese New Year every year.", syn: ["commemorate", "honor"] },
  "central": { zh: "中心的", ipa: "/ˈsentrəl/", pos: "adj.", ex: "The hotel is in a central location.", syn: ["middle", "core"] },
  "ceremony": { zh: "仪式", ipa: "/ˈserəməni/", pos: "n.", ex: "The wedding ceremony was beautiful.", syn: ["ritual", "event"] },
  "certain": { zh: "确定的", ipa: "/ˈsɜːrtən/", pos: "adj.", ex: "I am certain that he will come.", syn: ["sure", "definite"] },
  "chain": { zh: "链条；连锁", ipa: "/tʃeɪn/", pos: "n.", ex: "The restaurant is part of a chain.", syn: ["series", "sequence"] },
  "chairman": { zh: "主席", ipa: "/ˈtʃeərman/", pos: "n.", ex: "The chairman opened the meeting.", syn: ["president", "head"] },
  "challenge": { zh: "挑战", ipa: "/ˈtʃælɪndʒ/", pos: "n./v.", ex: "Climate change is a global challenge.", syn: ["dare", "test"] },
  "challenged": { zh: "受到挑战", ipa: "/ˈtʃælɪndʒd/", pos: "v.", ex: "The students challenged the teacher's opinion.", syn: ["questioned", "contested"] },
  "champion": { zh: "冠军", ipa: "/ˈtʃæmpiən/", pos: "n.", ex: "She became the world champion.", syn: ["winner", "victor"] },
  "chance": { zh: "机会", ipa: "/tʃɑːns/", pos: "n.", ex: "Give him a chance to prove himself.", syn: ["opportunity", "possibility"] },
  "channel": { zh: "频道；渠道", ipa: "/ˈtʃænəl/", pos: "n.", ex: "Which TV channel do you prefer?", syn: ["medium", "route"] },
  "chapter": { zh: "章节", ipa: "/ˈtʃæptər/", pos: "n.", ex: "Read chapter five for homework.", syn: ["section", "part"] },
  "character": { zh: "性格；角色", ipa: "/ˈkærəktər/", pos: "n.", ex: "She is a woman of strong character.", syn: ["personality", "nature"] },
  "characteristic": { zh: "特征", ipa: "/ˌkærəktəˈrɪstɪk/", pos: "n./adj.", ex: "Patience is a key characteristic of a teacher.", syn: ["trait", "feature"] },
  "charge": { zh: "收费；指控", ipa: "/tʃɑːrdʒ/", pos: "v./n.", ex: "Is there a charge for parking?", syn: ["fee", "cost"] },
  "charity": { zh: "慈善", ipa: "/ˈtʃærəti/", pos: "n.", ex: "She donated money to charity.", syn: ["philanthropy", "generosity"] },
  "chart": { zh: "图表", ipa: "/tʃɑːrt/", pos: "n.", ex: "The chart shows sales trends.", syn: ["graph", "diagram"] },
  "chase": { zh: "追赶", ipa: "/tʃeɪs/", pos: "v.", ex: "The dog likes to chase cats.", syn: ["pursue", "follow"] },
  "cheap": { zh: "便宜的", ipa: "/tʃiːp/", pos: "adj.", ex: "The food at this restaurant is cheap.", syn: ["inexpensive", "affordable"] },
  "cheat": { zh: "欺骗", ipa: "/tʃiːt/", pos: "v.", ex: "You should never cheat on an exam.", syn: ["deceive", "trick"] },
  "check": { zh: "检查", ipa: "/tʃek/", pos: "v./n.", ex: "Please check your email regularly.", syn: ["inspect", "examine"] },
  "chief": { zh: "主要的；首领", ipa: "/tʃiːf/", pos: "adj./n.", ex: "He is the chief executive of the company.", syn: ["main", "head"] },
  "child": { zh: "孩子", ipa: "/tʃaɪld/", pos: "n.", ex: "Every child deserves a good education.", syn: ["kid", "youngster"] },
  "children": { zh: "孩子们", ipa: "/ˈtʃɪldrən/", pos: "n.", ex: "The children played in the park.", syn: ["kids", "youngsters"] },
  "choice": { zh: "选择", ipa: "/tʃɔɪs/", pos: "n.", ex: "You have a difficult choice to make.", syn: ["option", "selection"] },
  "choose": { zh: "选择", ipa: "/tʃuːz/", pos: "v.", ex: "You can choose any color you like.", syn: ["select", "pick"] },
  "chronic": { zh: "慢性的", ipa: "/ˈkrɒnɪk/", pos: "adj.", ex: "He suffers from chronic back pain.", syn: ["persistent", "long-term"] },
  "circle": { zh: "圆；圈", ipa: "/ˈsɜːrkəl/", pos: "n.", ex: "The children sat in a circle.", syn: ["ring", "loop"] },
  "circumstance": { zh: "情况", ipa: "/ˈsɜːrkəmstæns/", pos: "n.", ex: "Under no circumstance should you give up.", syn: ["condition", "situation"] },
  "circumstances": { zh: "情况", ipa: "/ˈsɜːrkəmstænsɪz/", pos: "n.", ex: "The circumstances were beyond our control.", syn: ["conditions", "situations"] },
  "cite": { zh: "引用", ipa: "/saɪt/", pos: "v.", ex: "Please cite your sources in the paper.", syn: ["quote", "reference"] },
  "citizen": { zh: "公民", ipa: "/ˈsɪtɪzən/", pos: "n.", ex: "Every citizen has the right to vote.", syn: ["resident", "national"] },
  "civil": { zh: "民事的；文明的", ipa: "/ˈsɪvəl/", pos: "adj.", ex: "Civil rights are protected by law.", syn: ["civilian", "polite"] },
  "civilization": { zh: "文明", ipa: "/ˌsɪvəlaɪˈzeɪʃən/", pos: "n.", ex: "Ancient civilization left many monuments.", syn: ["culture", "society"] },
  "claim": { zh: "声称；索赔", ipa: "/kleɪm/", pos: "v./n.", ex: "She claimed that she was innocent.", syn: ["assert", "demand"] },
  "claimed": { zh: "声称了", ipa: "/kleɪmd/", pos: "v.", ex: "He claimed responsibility for the project.", syn: ["asserted", "stated"] },
  "clarify": { zh: "澄清", ipa: "/ˈklærɪfaɪ/", pos: "v.", ex: "Could you clarify what you mean?", syn: ["explain", "elucidate"] },
  "clash": { zh: "冲突", ipa: "/klæʃ/", pos: "n./v.", ex: "There was a clash between the two groups.", syn: ["conflict", "collision"] },
  "classic": { zh: "经典的", ipa: "/ˈklæsɪk/", pos: "adj.", ex: "This novel is a classic piece of literature.", syn: ["timeless", "traditional"] },
  "clean": { zh: "干净的", ipa: "/kliːn/", pos: "adj.", ex: "The room was spotlessly clean.", syn: ["tidy", "pure"] },
  "clear": { zh: "清楚的", ipa: "/klɪər/", pos: "adj.", ex: "The instructions were very clear.", syn: ["obvious", "evident"] },
  "clearly": { zh: "清楚地", ipa: "/ˈklɪəli/", pos: "adv.", ex: "She clearly explained the procedure.", syn: ["obviously", "evidently"] },
  "clever": { zh: "聪明的", ipa: "/ˈklevər/", pos: "adj.", ex: "She found a clever solution to the problem.", syn: ["smart", "intelligent"] },
  "client": { zh: "客户", ipa: "/ˈklaɪənt/", pos: "n.", ex: "The client was satisfied with the service.", syn: ["customer", "patron"] },
  "climate": { zh: "气候", ipa: "/ˈklaɪmət/", pos: "n.", ex: "Climate change is a serious global issue.", syn: ["weather", "conditions"] },
  "climb": { zh: "攀登", ipa: "/klaɪm/", pos: "v.", ex: "They plan to climb the mountain next week.", syn: ["ascend", "scale"] },
  "cling": { zh: "紧抓", ipa: "/klɪŋ/", pos: "v.", ex: "The child clung to his mother.", syn: ["hold", "grip"] },
  "close": { zh: "关闭；亲密的", ipa: "/kləʊz/", pos: "v./adj.", ex: "Please close the door behind you.", syn: ["shut", "near"] },
  "closely": { zh: "紧密地", ipa: "/ˈkləʊsli/", pos: "adv.", ex: "The police watched the suspect closely.", syn: ["carefully", "attentively"] },
  "cloud": { zh: "云", ipa: "/klaʊd/", pos: "n.", ex: "Dark clouds gathered in the sky.", syn: ["mist", "haze"] },
  "clue": { zh: "线索", ipa: "/kluː/", pos: "n.", ex: "The detective found an important clue.", syn: ["hint", "lead"] },
  "coach": { zh: "教练", ipa: "/kəʊtʃ/", pos: "n.", ex: "The coach trained the team every day.", syn: ["trainer", "instructor"] },
  "coal": { zh: "煤", ipa: "/kəʊl/", pos: "n.", ex: "The factory is powered by coal.", syn: ["charcoal", "fuel"] },
  "coalition": { zh: "联盟", ipa: "/ˌkəʊəˈlɪʃən/", pos: "n.", ex: "The parties formed a coalition government.", syn: ["alliance", "union"] },
  "code": { zh: "代码；法规", ipa: "/kəʊd/", pos: "n.", ex: "Follow the dress code at work.", syn: ["system", "cipher"] },
  "collapse": { zh: "倒塌", ipa: "/kəˈlæps/", pos: "v./n.", ex: "The old building collapsed during the earthquake.", syn: ["fall", "crumble"] },
  "colleague": { zh: "同事", ipa: "/ˈkɒliːɡ/", pos: "n.", ex: "She discussed the plan with her colleague.", syn: ["coworker", "associate"] },
  "colleagues": { zh: "同事们", ipa: "/ˈkɒliːɡz/", pos: "n.", ex: "My colleagues are very supportive.", syn: ["coworkers", "peers"] },
  "collect": { zh: "收集", ipa: "/kəˈlekt/", pos: "v.", ex: "She likes to collect stamps.", syn: ["gather", "accumulate"] },
  "collection": { zh: "收藏", ipa: "/kəˈlekʃən/", pos: "n.", ex: "The museum has an impressive art collection.", syn: ["assortment", "compilation"] },
  "colony": { zh: "殖民地", ipa: "/ˈkɒləni/", pos: "n.", ex: "The country was once a British colony.", syn: ["settlement", "territory"] },
  "column": { zh: "柱；栏", ipa: "/ˈkɒləm/", pos: "n.", ex: "She writes a weekly newspaper column.", syn: ["pillar", "post"] },
  "combination": { zh: "组合", ipa: "/ˌkɒmbɪˈneɪʃən/", pos: "n.", ex: "It is a combination of art and science.", syn: ["mixture", "blend"] },
  "combine": { zh: "结合", ipa: "/kəmˈbaɪn/", pos: "v.", ex: "Combine the flour and sugar together.", syn: ["merge", "unite"] },
  "comfort": { zh: "舒适", ipa: "/ˈkʌmfərt/", pos: "n./v.", ex: "The hotel offers great comfort.", syn: ["ease", "relief"] },
  "comfortable": { zh: "舒适的", ipa: "/ˈkʌmftəbəl/", pos: "adj.", ex: "This chair is very comfortable.", syn: ["cozy", "pleasant"] },
  "command": { zh: "命令", ipa: "/kəˈmɑːnd/", pos: "n./v.", ex: "The officer gave a command to advance.", syn: ["order", "directive"] },
  "comment": { zh: "评论", ipa: "/ˈkɒment/", pos: "n./v.", ex: "She made a helpful comment about the essay.", syn: ["remark", "observation"] },
  "commercial": { zh: "商业的", ipa: "/kəˈmɜːrʃəl/", pos: "adj.", ex: "The commercial district is very busy.", syn: ["business", "trade"] },
  "commission": { zh: "委员会；佣金", ipa: "/kəˈmɪʃən/", pos: "n.", ex: "He earns a commission on every sale.", syn: ["committee", "fee"] },
  "commit": { zh: "承诺；犯罪", ipa: "/kəˈmɪt/", pos: "v.", ex: "We must commit to protecting the environment.", syn: ["pledge", "dedicate"] },
  "commitment": { zh: "承诺", ipa: "/kəˈmɪtmənt/", pos: "n.", ex: "She has a strong commitment to her work.", syn: ["dedication", "pledge"] },
  "committed": { zh: "承诺的", ipa: "/kəˈmɪtɪd/", pos: "adj.", ex: "He is committed to his studies.", syn: ["dedicated", "devoted"] },
  "committee": { zh: "委员会", ipa: "/kəˈmɪti/", pos: "n.", ex: "The committee reviewed the proposal.", syn: ["board", "panel"] },
  "common": { zh: "普通的", ipa: "/ˈkɒmən/", pos: "adj.", ex: "It is a common problem among students.", syn: ["usual", "ordinary"] },
  "commonly": { zh: "通常", ipa: "/ˈkɒmənli/", pos: "adv.", ex: "This disease is commonly found in tropical areas.", syn: ["usually", "frequently"] },
  "communicate": { zh: "交流", ipa: "/kəˈmjuːnɪkeɪt/", pos: "v.", ex: "It is important to communicate clearly.", syn: ["convey", "express"] },
  "communication": { zh: "交流", ipa: "/kəˌmjuːnɪˈkeɪʃən/", pos: "n.", ex: "Good communication is essential in a team.", syn: ["dialogue", "exchange"] },
  "community": { zh: "社区", ipa: "/kəˈmjuːnəti/", pos: "n.", ex: "The community organized a clean-up event.", syn: ["neighborhood", "society"] },
  "companion": { zh: "同伴", ipa: "/kəmˈpænjən/", pos: "n.", ex: "She was a loyal companion throughout the trip.", syn: ["partner", "friend"] },
  "company": { zh: "公司", ipa: "/ˈkʌmpəni/", pos: "n.", ex: "He started his own company last year.", syn: ["firm", "business"] },
  "compare": { zh: "比较", ipa: "/kəmˈpeər/", pos: "v.", ex: "Compare the prices before you buy.", syn: ["contrast", "evaluate"] },
  "compared": { zh: "与…相比", ipa: "/kəmˈpeərd/", pos: "v.", ex: "Compared to last year, sales have increased.", syn: ["contrasted", "measured against"] },
  "comparison": { zh: "比较", ipa: "/kəmˈpærɪsən/", pos: "n.", ex: "There is no comparison between the two.", syn: ["contrast", "analogy"] },
  "compel": { zh: "强迫", ipa: "/kəmˈpel/", pos: "v.", ex: "The evidence compelled him to confess.", syn: ["force", "coerce"] },
  "compensate": { zh: "补偿", ipa: "/ˈkɒmpenseɪt/", pos: "v.", ex: "The company will compensate for the loss.", syn: ["reimburse", "repay"] },
  "compensation": { zh: "补偿", ipa: "/ˌkɒmpenˈseɪʃən/", pos: "n.", ex: "Workers received compensation for overtime.", syn: ["payment", "reimbursement"] },
  "compete": { zh: "竞争", ipa: "/kəmˈpiːt/", pos: "v.", ex: "The athletes compete for the gold medal.", syn: ["contend", "rival"] },
  "competition": { zh: "竞争", ipa: "/ˌkɒmpəˈtɪʃən/", pos: "n.", ex: "The competition for the job was fierce.", syn: ["contest", "rivalry"] },
  "competitive": { zh: "竞争的", ipa: "/kəmˈpetətɪv/", pos: "adj.", ex: "The market is very competitive.", syn: ["ambitious", "aggressive"] },
  "complain": { zh: "抱怨", ipa: "/kəmˈpleɪn/", pos: "v.", ex: "Customers often complain about the service.", syn: ["grumble", "protest"] },
  "complaint": { zh: "投诉", ipa: "/kəmˈpleɪnt/", pos: "n.", ex: "She filed a complaint with the manager.", syn: ["grievance", "objection"] },
  "complete": { zh: "完成", ipa: "/kəmˈpliːt/", pos: "v./adj.", ex: "Please complete the form by Friday.", syn: ["finish", "total"] },
  "completed": { zh: "完成了", ipa: "/kəmˈpliːtɪd/", pos: "v.", ex: "The project was completed on schedule.", syn: ["finished", "accomplished"] },
  "completely": { zh: "完全地", ipa: "/kəmˈpliːtli/", pos: "adv.", ex: "I completely agree with you.", syn: ["totally", "entirely"] },
  "complex": { zh: "复杂的", ipa: "/ˈkɒmpleks/", pos: "adj.", ex: "The problem is more complex than we thought.", syn: ["complicated", "intricate"] },
  "complexity": { zh: "复杂性", ipa: "/kəmˈpleksəti/", pos: "n.", ex: "The complexity of the system is impressive.", syn: ["intricacy", "difficulty"] },
  "component": { zh: "组成部分", ipa: "/kəmˈpəʊnənt/", pos: "n.", ex: "Each component plays an important role.", syn: ["part", "element"] },
  "compose": { zh: "组成；创作", ipa: "/kəmˈpəʊz/", pos: "v.", ex: "She composed a beautiful piece of music.", syn: ["create", "write"] },
  "composition": { zh: "作文；组成", ipa: "/ˌkɒmpəˈzɪʃən/", pos: "n.", ex: "The composition of the team was diverse.", syn: ["structure", "makeup"] },
  "comprehensive": { zh: "综合的", ipa: "/ˌkɒmprɪˈhensɪv/", pos: "adj.", ex: "We need a comprehensive review of the policy.", syn: ["thorough", "complete"] },
  "comprise": { zh: "包含", ipa: "/kəmˈpraɪz/", pos: "v.", ex: "The team comprises ten members.", syn: ["consist of", "include"] },
  "compromise": { zh: "妥协", ipa: "/ˈkɒmprəmaɪz/", pos: "n./v.", ex: "Both sides need to reach a compromise.", syn: ["agreement", "settlement"] },
  "concentrate": { zh: "集中", ipa: "/ˈkɒnsəntreɪt/", pos: "v.", ex: "I need to concentrate on my studies.", syn: ["focus", "center"] },
  "concentration": { zh: "集中", ipa: "/ˌkɒnsənˈtreɪʃən/", pos: "n.", ex: "This task requires great concentration.", syn: ["focus", "attention"] },
  "concept": { zh: "概念", ipa: "/ˈkɒnsept/", pos: "n.", ex: "The concept of justice is complex.", syn: ["idea", "notion"] },
  "concern": { zh: "关心；担忧", ipa: "/kənˈsɜːrn/", pos: "n./v.", ex: "Safety is our primary concern.", syn: ["worry", "care"] },
  "concerned": { zh: "担心的", ipa: "/kənˈsɜːrnd/", pos: "adj.", ex: "I am concerned about his health.", syn: ["worried", "anxious"] },
  "conclude": { zh: "总结", ipa: "/kənˈkluːd/", pos: "v.", ex: "She concluded her speech with a quote.", syn: ["finish", "end"] },
  "conclusion": { zh: "结论", ipa: "/kənˈkluːʒən/", pos: "n.", ex: "In conclusion, we need more research.", syn: ["ending", "result"] },
  "concrete": { zh: "具体的；混凝土", ipa: "/ˈkɒŋkriːt/", pos: "adj./n.", ex: "We need concrete evidence to prove it.", syn: ["solid", "tangible"] },
  "condition": { zh: "条件；状况", ipa: "/kənˈdɪʃən/", pos: "n.", ex: "The car is in excellent condition.", syn: ["state", "situation"] },
  "conditions": { zh: "条件", ipa: "/kənˈdɪʃənz/", pos: "n.", ex: "Working conditions have improved greatly.", syn: ["circumstances", "terms"] },
  "conduct": { zh: "进行；行为", ipa: "/kənˈdʌkt/", pos: "v./n.", ex: "We will conduct a survey next week.", syn: ["perform", "carry out"] },
  "conducted": { zh: "进行了", ipa: "/kənˈdʌktɪd/", pos: "v.", ex: "The experiment was conducted carefully.", syn: ["performed", "carried out"] },
  "conference": { zh: "会议", ipa: "/ˈkɒnfərəns/", pos: "n.", ex: "She presented her findings at the conference.", syn: ["meeting", "summit"] },
  "confidence": { zh: "信心", ipa: "/ˈkɒnfɪdəns/", pos: "n.", ex: "She spoke with great confidence.", syn: ["assurance", "self-assurance"] },
  "confident": { zh: "自信的", ipa: "/ˈkɒnfɪdənt/", pos: "adj.", ex: "She felt confident about the exam.", syn: ["assured", "self-assured"] },
  "confirm": { zh: "确认", ipa: "/kənˈfɜːrm/", pos: "v.", ex: "Please confirm your reservation by email.", syn: ["verify", "validate"] },
  "confirmed": { zh: "确认了", ipa: "/kənˈfɜːrmd/", pos: "v.", ex: "The news was confirmed by the police.", syn: ["verified", "validated"] },
  "conflict": { zh: "冲突", ipa: "/ˈkɒnflɪkt/", pos: "n.", ex: "There is a conflict between the two groups.", syn: ["dispute", "clash"] },
  "confront": { zh: "面对", ipa: "/kənˈfrʌnt/", pos: "v.", ex: "We must confront the problem directly.", syn: ["face", "tackle"] },
  "confuse": { zh: "使困惑", ipa: "/kənˈfjuːz/", pos: "v.", ex: "The instructions confused many students.", syn: ["puzzle", "bewilder"] },
  "confusion": { zh: "混乱", ipa: "/kənˈfjuːʒən/", pos: "n.", ex: "There was some confusion about the schedule.", syn: ["disorder", "chaos"] },
  "connect": { zh: "连接", ipa: "/kəˈnekt/", pos: "v.", ex: "Connect the cable to the computer.", syn: ["link", "join"] },
  "connected": { zh: "连接的", ipa: "/kəˈnektɪd/", pos: "adj.", ex: "All the devices are connected to the internet.", syn: ["linked", "joined"] },
  "connection": { zh: "连接", ipa: "/kəˈnekʃən/", pos: "n.", ex: "There is a connection between diet and health.", syn: ["link", "relationship"] },
  "conquer": { zh: "征服", ipa: "/ˈkɒŋkər/", pos: "v.", ex: "She conquered her fear of public speaking.", syn: ["overcome", "defeat"] },
  "conscience": { zh: "良心", ipa: "/ˈkɒnʃəns/", pos: "n.", ex: "He has a guilty conscience.", syn: ["morality", "sense of right"] },
  "conscious": { zh: "有意识的", ipa: "/ˈkɒnʃəs/", pos: "adj.", ex: "She made a conscious effort to be kind.", syn: ["aware", "deliberate"] },
  "consciousness": { zh: "意识", ipa: "/ˈkɒnʃəsnəs/", pos: "n.", ex: "He lost consciousness after the accident.", syn: ["awareness", "perception"] },
  "consensus": { zh: "共识", ipa: "/kənˈsensəs/", pos: "n.", ex: "The committee reached a consensus.", syn: ["agreement", "accord"] },
  "consequence": { zh: "后果", ipa: "/ˈkɒnsɪkwəns/", pos: "n.", ex: "Consider the consequences of your actions.", syn: ["result", "outcome"] },
  "consequences": { zh: "后果", ipa: "/ˈkɒnsɪkwənsɪz/", pos: "n.", ex: "Pollution has serious consequences for health.", syn: ["results", "effects"] },
  "conservation": { zh: "保护", ipa: "/ˌkɒnsəˈveɪʃən/", pos: "n.", ex: "Wildlife conservation is very important.", syn: ["preservation", "protection"] },
  "conservative": { zh: "保守的", ipa: "/kənˈsɜːrvətɪv/", pos: "adj.", ex: "He has conservative political views.", syn: ["traditional", "conventional"] },
  "considerable": { zh: "相当大的", ipa: "/kənˈsɪdərəbəl/", pos: "adj.", ex: "There has been considerable improvement.", syn: ["significant", "substantial"] },
  "considerably": { zh: "相当地", ipa: "/kənˈsɪdərəbli/", pos: "adv.", ex: "Prices have risen considerably this year.", syn: ["significantly", "substantially"] },
  "consist": { zh: "由…组成", ipa: "/kənˈsɪst/", pos: "v.", ex: "The team consists of five members.", syn: ["comprise", "be composed of"] },
  "consistent": { zh: "一致的", ipa: "/kənˈsɪstənt/", pos: "adj.", ex: "Her results are consistent with the theory.", syn: ["steady", "uniform"] },
  "constantly": { zh: "不断地", ipa: "/ˈkɒnstəntli/", pos: "adv.", ex: "Technology is constantly evolving.", syn: ["continuously", "always"] },
  "constitute": { zh: "构成", ipa: "/ˈkɒnstɪtjuːt/", pos: "v.", ex: "These items constitute a complete set.", syn: ["form", "make up"] },
  "construct": { zh: "建造", ipa: "/kənˈstrʌkt/", pos: "v.", ex: "They plan to construct a new bridge.", syn: ["build", "erect"] },
  "construction": { zh: "建筑", ipa: "/kənˈstrʌkʃən/", pos: "n.", ex: "The construction of the bridge took two years.", syn: ["building", "erection"] },
  "consult": { zh: "咨询", ipa: "/kənˈsʌlt/", pos: "v.", ex: "You should consult a doctor about the pain.", syn: ["ask", "seek advice"] },
  "consume": { zh: "消耗", ipa: "/kənˈsjuːm/", pos: "v.", ex: "We consume too much energy.", syn: ["use", "devour"] },
  "consumer": { zh: "消费者", ipa: "/kənˈsjuːmər/", pos: "n.", ex: "Consumers demand better products.", syn: ["buyer", "customer"] },
  "consumption": { zh: "消费", ipa: "/kənˈsʌmpʃən/", pos: "n.", ex: "Energy consumption has increased.", syn: ["usage", "use"] },
  "contact": { zh: "联系", ipa: "/ˈkɒntækt/", pos: "n./v.", ex: "Please contact me if you have questions.", syn: ["reach", "touch"] },
  "contain": { zh: "包含", ipa: "/kənˈteɪn/", pos: "v.", ex: "The box contains old photographs.", syn: ["hold", "include"] },
  "contemporary": { zh: "当代的", ipa: "/kənˈtempərəri/", pos: "adj.", ex: "She studies contemporary art.", syn: ["modern", "current"] },
  "content": { zh: "内容；满意的", ipa: "/ˈkɒntent/", pos: "n./adj.", ex: "The content of the book is fascinating.", syn: ["material", "substance"] },
  "contest": { zh: "竞赛", ipa: "/ˈkɒntest/", pos: "n.", ex: "She won first place in the contest.", syn: ["competition", "tournament"] },
  "context": { zh: "背景；上下文", ipa: "/ˈkɒntekst/", pos: "n.", ex: "You need to understand the context.", syn: ["background", "setting"] },
  "contract": { zh: "合同", ipa: "/ˈkɒntrækt/", pos: "n.", ex: "They signed a one-year contract.", syn: ["agreement", "deal"] },
  "contrast": { zh: "对比", ipa: "/ˈkɒntrɑːst/", pos: "n./v.", ex: "In contrast to the north, the south is warm.", syn: ["difference", "distinction"] },
  "contribute": { zh: "贡献", ipa: "/kənˈtrɪbjuːt/", pos: "v.", ex: "Everyone should contribute to the project.", syn: ["give", "donate"] },
  "contribution": { zh: "贡献", ipa: "/ˌkɒntrɪˈbjuːʃən/", pos: "n.", ex: "Her contribution to science is remarkable.", syn: ["donation", "input"] },
  "control": { zh: "控制", ipa: "/kənˈtrəʊl/", pos: "v./n.", ex: "She lost control of the vehicle.", syn: ["manage", "regulate"] },
  "controversial": { zh: "有争议的", ipa: "/ˌkɒntrəˈvɜːrʃəl/", pos: "adj.", ex: "The decision was highly controversial.", syn: ["debatable", "disputed"] },
  "controversy": { zh: "争议", ipa: "/ˈkɒntrəvɜːrsi/", pos: "n.", ex: "The new law sparked controversy.", syn: ["debate", "dispute"] },
  "convenient": { zh: "方便的", ipa: "/kənˈviːniənt/", pos: "adj.", ex: "The store is in a convenient location.", syn: ["handy", "accessible"] },
  "conventional": { zh: "传统的", ipa: "/kənˈvenʃənəl/", pos: "adj.", ex: "She prefers conventional teaching methods.", syn: ["traditional", "standard"] },
  "conversation": { zh: "对话", ipa: "/ˌkɒnvəˈseɪʃən/", pos: "n.", ex: "We had a long conversation about the future.", syn: ["discussion", "talk"] },
  "convert": { zh: "转换", ipa: "/kənˈvɜːrt/", pos: "v.", ex: "We need to convert the file format.", syn: ["transform", "change"] },
  "conviction": { zh: "信念；定罪", ipa: "/kənˈvɪkʃən/", pos: "n.", ex: "She spoke with great conviction.", syn: ["belief", "certainty"] },
  "convince": { zh: "说服", ipa: "/kənˈvɪns/", pos: "v.", ex: "She tried to convince him to stay.", syn: ["persuade", "sway"] },
  "convinced": { zh: "确信的", ipa: "/kənˈvɪnst/", pos: "adj.", ex: "I am convinced that he is telling the truth.", syn: ["certain", "sure"] },
  "cooperate": { zh: "合作", ipa: "/kəʊˈɒpəreɪt/", pos: "v.", ex: "The two companies agreed to cooperate.", syn: ["collaborate", "work together"] },
  "cooperation": { zh: "合作", ipa: "/kəʊˌɒpəˈreɪʃən/", pos: "n.", ex: "International cooperation is essential.", syn: ["collaboration", "teamwork"] },
  "coordinate": { zh: "协调", ipa: "/kəʊˈɔːrdɪneɪt/", pos: "v.", ex: "We need to coordinate our efforts.", syn: ["organize", "arrange"] },
  "cope": { zh: "应对", ipa: "/kəʊp/", pos: "v.", ex: "She learned to cope with stress.", syn: ["manage", "handle"] },
  "core": { zh: "核心", ipa: "/kɔːr/", pos: "n./adj.", ex: "Innovation is at the core of our strategy.", syn: ["center", "heart"] },
  "corner": { zh: "角落", ipa: "/ˈkɔːrnər/", pos: "n.", ex: "There is a café on the corner.", syn: ["edge", "bend"] },
  "corporate": { zh: "企业的", ipa: "/ˈkɔːrpərət/", pos: "adj.", ex: "The corporate culture encourages innovation.", syn: ["business", "company"] },
  "correct": { zh: "正确的", ipa: "/kəˈrekt/", pos: "adj.", ex: "Your answer is correct.", syn: ["right", "accurate"] },
  "correspond": { zh: "通信；对应", ipa: "/ˌkɒrɪˈspɒnd/", pos: "v.", ex: "The results correspond with our predictions.", syn: ["match", "agree"] },
  "cost": { zh: "费用", ipa: "/kɒst/", pos: "n./v.", ex: "The cost of living has increased.", syn: ["price", "expense"] },
  "council": { zh: "委员会", ipa: "/ˈkaʊnsəl/", pos: "n.", ex: "The city council approved the plan.", syn: ["committee", "board"] },
  "count": { zh: "计算；重要", ipa: "/kaʊnt/", pos: "v.", ex: "Every vote should count.", syn: ["calculate", "matter"] },
  "countless": { zh: "无数的", ipa: "/ˈkaʊntləs/", pos: "adj.", ex: "She has helped countless people.", syn: ["numerous", "innumerable"] },
  "country": { zh: "国家", ipa: "/ˈkʌntri/", pos: "n.", ex: "China is a large country.", syn: ["nation", "state"] },
  "couple": { zh: "一对；几个", ipa: "/ˈkʌpəl/", pos: "n.", ex: "I have a couple of questions.", syn: ["pair", "few"] },
  "courage": { zh: "勇气", ipa: "/ˈkʌrɪdʒ/", pos: "n.", ex: "It takes courage to speak the truth.", syn: ["bravery", "valor"] },
  "course": { zh: "课程；过程", ipa: "/kɔːrs/", pos: "n.", ex: "She enrolled in a math course.", syn: ["class", "program"] },
  "court": { zh: "法庭", ipa: "/kɔːrt/", pos: "n.", ex: "The case was brought to court.", syn: ["tribunal", "bench"] },
  "cover": { zh: "覆盖", ipa: "/ˈkʌvər/", pos: "v./n.", ex: "Snow covered the ground completely.", syn: ["blanket", "shield"] },
  "coverage": { zh: "覆盖范围", ipa: "/ˈkʌvərɪdʒ/", pos: "n.", ex: "The media coverage was extensive.", syn: ["reporting", "reach"] },
  "crack": { zh: "裂缝", ipa: "/kræk/", pos: "n./v.", ex: "There is a crack in the wall.", syn: ["split", "fracture"] },
  "craft": { zh: "工艺；手艺", ipa: "/krɑːft/", pos: "n.", ex: "She learned the craft of pottery.", syn: ["skill", "art"] },
  "crash": { zh: "碰撞", ipa: "/kræʃ/", pos: "n./v.", ex: "The car crash damaged both vehicles.", syn: ["collision", "wreck"] },
  "creative": { zh: "创造性的", ipa: "/kriˈeɪtɪv/", pos: "adj.", ex: "She has a creative mind.", syn: ["imaginative", "inventive"] },
  "creature": { zh: "生物", ipa: "/ˈkriːtʃər/", pos: "n.", ex: "The ocean is full of strange creatures.", syn: ["being", "animal"] },
  "credit": { zh: "信用；学分", ipa: "/ˈkredɪt/", pos: "n.", ex: "She deserves credit for her hard work.", syn: ["recognition", "acknowledgment"] },
  "crew": { zh: "全体船员；工作人员", ipa: "/kruː/", pos: "n.", ex: "The film crew arrived early in the morning.", syn: ["team", "staff"] },
  "crime": { zh: "犯罪", ipa: "/kraɪm/", pos: "n.", ex: "The crime rate has decreased.", syn: ["offense", "violation"] },
  "criminal": { zh: "犯罪的；罪犯", ipa: "/ˈkrɪmɪnəl/", pos: "adj./n.", ex: "Criminal behavior will be punished.", syn: ["illegal", "offender"] },
  "crisis": { zh: "危机", ipa: "/ˈkraɪsɪs/", pos: "n.", ex: "The country is facing an economic crisis.", syn: ["emergency", "disaster"] },
  "criteria": { zh: "标准", ipa: "/kraɪˈtɪəriə/", pos: "n.", ex: "The criteria for selection are very strict.", syn: ["standards", "requirements"] },
  "criterion": { zh: "标准", ipa: "/kraɪˈtɪəriən/", pos: "n.", ex: "Quality is an important criterion.", syn: ["standard", "measure"] },
  "critic": { zh: "评论家", ipa: "/ˈkrɪtɪk/", pos: "n.", ex: "The film received praise from every critic.", syn: ["reviewer", "commentator"] },
  "critical": { zh: "关键的；批评的", ipa: "/ˈkrɪtɪkəl/", pos: "adj.", ex: "This is a critical moment in history.", syn: ["crucial", "vital"] },
  "criticism": { zh: "批评", ipa: "/ˈkrɪtɪsɪzəm/", pos: "n.", ex: "The plan faced strong criticism.", syn: ["disapproval", "censure"] },
  "crop": { zh: "庄稼", ipa: "/krɒp/", pos: "n.", ex: "The farmer harvested the crop.", syn: ["harvest", "yield"] },
  "cross": { zh: "穿过", ipa: "/krɒs/", pos: "v.", ex: "Be careful when you cross the road.", syn: ["traverse", "pass"] },
  "crowd": { zh: "人群", ipa: "/kraʊd/", pos: "n.", ex: "A large crowd gathered in the square.", syn: ["mob", "throng"] },
  "crucial": { zh: "关键的", ipa: "/ˈkruːʃəl/", pos: "adj.", ex: "This is a crucial step in the process.", syn: ["critical", "vital"] },
  "cruel": { zh: "残忍的", ipa: "/ˈkruːəl/", pos: "adj.", ex: "It is cruel to hurt animals.", syn: ["harsh", "brutal"] },
  "culture": { zh: "文化", ipa: "/ˈkʌltʃər/", pos: "n.", ex: "Chinese culture has a long history.", syn: ["civilization", "heritage"] },
  "cultural": { zh: "文化的", ipa: "/ˈkʌltʃərəl/", pos: "adj.", ex: "We appreciate cultural diversity.", syn: ["artistic", "social"] },
  "cure": { zh: "治愈", ipa: "/kjʊər/", pos: "n./v.", ex: "Scientists are searching for a cure.", syn: ["remedy", "treatment"] },
  "curious": { zh: "好奇的", ipa: "/ˈkjʊəriəs/", pos: "adj.", ex: "The child is curious about everything.", syn: ["inquisitive", "interested"] },
  "current": { zh: "当前的", ipa: "/ˈkʌrənt/", pos: "adj.", ex: "The current situation is improving.", syn: ["present", "ongoing"] },
  "currently": { zh: "目前", ipa: "/ˈkʌrəntli/", pos: "adv.", ex: "She is currently studying abroad.", syn: ["now", "presently"] },
  "curriculum": { zh: "课程", ipa: "/kəˈrɪkjʊləm/", pos: "n.", ex: "The school updated its curriculum.", syn: ["syllabus", "program"] },
  "custom": { zh: "习俗；定制的", ipa: "/ˈkʌstəm/", pos: "n.", ex: "It is a local custom to welcome visitors.", syn: ["tradition", "practice"] },
  "customer": { zh: "顾客", ipa: "/ˈkʌstəmər/", pos: "n.", ex: "The customer asked for a refund.", syn: ["client", "buyer"] },
  "cycle": { zh: "循环", ipa: "/ˈsaɪkəl/", pos: "n.", ex: "Life is a continuous cycle.", syn: ["rotation", "loop"] },
  "daily": { zh: "每日的", ipa: "/ˈdeɪli/", pos: "adj.", ex: "She reads the daily newspaper.", syn: ["everyday", "regular"] },
  "damage": { zh: "损害", ipa: "/ˈdæmɪdʒ/", pos: "n./v.", ex: "The storm caused significant damage.", syn: ["harm", "destruction"] },
  "danger": { zh: "危险", ipa: "/ˈdeɪndʒər/", pos: "n.", ex: "The animal was in danger of extinction.", syn: ["risk", "hazard"] },
  "dangerous": { zh: "危险的", ipa: "/ˈdeɪndʒərəs/", pos: "adj.", ex: "It is dangerous to drive too fast.", syn: ["hazardous", "risky"] },
  "dare": { zh: "敢", ipa: "/deər/", pos: "v.", ex: "How dare you speak to me like that!", syn: ["venture", "risk"] },
  "dark": { zh: "黑暗的", ipa: "/dɑːrk/", pos: "adj.", ex: "It gets dark early in winter.", syn: ["dim", "gloomy"] },
  "data": { zh: "数据", ipa: "/ˈdeɪtə/", pos: "n.", ex: "The data supports our theory.", syn: ["information", "facts"] },
  "date": { zh: "日期", ipa: "/deɪt/", pos: "n.", ex: "What is the date today?", syn: ["day", "time"] },
  "daughter": { zh: "女儿", ipa: "/ˈdɔːtər/", pos: "n.", ex: "Their daughter is studying medicine.", syn: ["girl", "offspring"] },
  "deal": { zh: "交易；处理", ipa: "/diːl/", pos: "n./v.", ex: "We made a deal with the supplier.", syn: ["agreement", "transaction"] },
  "dealing": { zh: "交往", ipa: "/ˈdiːlɪŋ/", pos: "n.", ex: "He has been dealing with the issue.", syn: ["handling", "managing"] },
  "dear": { zh: "亲爱的", ipa: "/dɪər/", pos: "adj.", ex: "Dear friends, thank you for coming.", syn: ["beloved", "precious"] },
  "death": { zh: "死亡", ipa: "/deθ/", pos: "n.", ex: "The death of the king shocked the nation.", syn: ["demise", "passing"] },
  "debate": { zh: "辩论", ipa: "/dɪˈbeɪt/", pos: "n./v.", ex: "There was a heated debate on the topic.", syn: ["discussion", "argument"] },
  "debt": { zh: "债务", ipa: "/det/", pos: "n.", ex: "He is struggling to pay off his debt.", syn: ["liability", "obligation"] },
  "decade": { zh: "十年", ipa: "/ˈdekeɪd/", pos: "n.", ex: "The country changed a lot in the past decade.", syn: ["ten years", "period"] },
  "decent": { zh: "体面的", ipa: "/ˈdiːsənt/", pos: "adj.", ex: "He earns a decent salary.", syn: ["proper", "respectable"] },
  "decision": { zh: "决定", ipa: "/dɪˈsɪʒən/", pos: "n.", ex: "Making the right decision is important.", syn: ["choice", "judgment"] },
  "declare": { zh: "宣布", ipa: "/dɪˈkleər/", pos: "v.", ex: "The government declared a state of emergency.", syn: ["announce", "proclaim"] },
  "decline": { zh: "下降；拒绝", ipa: "/dɪˈklaɪn/", pos: "v./n.", ex: "The population continues to decline.", syn: ["decrease", "refuse"] },
  "decrease": { zh: "减少", ipa: "/dɪˈkriːs/", pos: "v./n.", ex: "Sales decreased by ten percent.", syn: ["reduce", "diminish"] },
  "dedicate": { zh: "献身于", ipa: "/ˈdedɪkeɪt/", pos: "v.", ex: "She dedicated her life to teaching.", syn: ["devote", "commit"] },
  "dedicated": { zh: "专注的", ipa: "/ˈdedɪkeɪtɪd/", pos: "adj.", ex: "She is a dedicated teacher.", syn: ["committed", "devoted"] },
  "deem": { zh: "认为", ipa: "/diːm/", pos: "v.", ex: "The proposal was deemed acceptable.", syn: ["consider", "regard"] },
  "deep": { zh: "深的", ipa: "/diːp/", pos: "adj.", ex: "The lake is very deep.", syn: ["profound", "intense"] },
  "deeply": { zh: "深深地", ipa: "/ˈdiːpli/", pos: "adv.", ex: "She was deeply moved by the story.", syn: ["profoundly", "intensely"] },
  "defeat": { zh: "打败", ipa: "/dɪˈfiːt/", pos: "v./n.", ex: "They defeated the enemy in battle.", syn: ["beat", "overcome"] },
  "defend": { zh: "防御", ipa: "/dɪˈfend/", pos: "v.", ex: "We must defend our rights.", syn: ["protect", "guard"] },
  "defense": { zh: "防御", ipa: "/dɪˈfens/", pos: "n.", ex: "The country strengthened its defense.", syn: ["protection", "shield"] },
  "define": { zh: "定义", ipa: "/dɪˈfaɪn/", pos: "v.", ex: "How do you define success?", syn: ["describe", "explain"] },
  "defined": { zh: "定义了的", ipa: "/dɪˈfaɪnd/", pos: "v.", ex: "The roles are clearly defined.", syn: ["specified", "determined"] },
  "definitely": { zh: "肯定地", ipa: "/ˈdefɪnətli/", pos: "adv.", ex: "I will definitely attend the party.", syn: ["certainly", "absolutely"] },
  "definition": { zh: "定义", ipa: "/ˌdefɪˈnɪʃən/", pos: "n.", ex: "What is the definition of this word?", syn: ["meaning", "explanation"] },
  "degree": { zh: "程度；学位", ipa: "/dɪˈɡriː/", pos: "n.", ex: "She earned a degree in biology.", syn: ["level", "extent"] },
  "delay": { zh: "延迟", ipa: "/dɪˈleɪ/", pos: "n./v.", ex: "The flight was delayed by two hours.", syn: ["postpone", "hold up"] },
  "deliberate": { zh: "故意的", ipa: "/dɪˈlɪbərət/", pos: "adj.", ex: "It was a deliberate act of sabotage.", syn: ["intentional", "planned"] },
  "deliberately": { zh: "故意地", ipa: "/dɪˈlɪbərətli/", pos: "adv.", ex: "She deliberately ignored his calls.", syn: ["intentionally", "on purpose"] },
  "delicate": { zh: "精致的", ipa: "/ˈdelɪkət/", pos: "adj.", ex: "The flowers are very delicate.", syn: ["fragile", "fine"] },
  "deliver": { zh: "递送", ipa: "/dɪˈlɪvər/", pos: "v.", ex: "The package will be delivered tomorrow.", syn: ["send", "transport"] },
  "delivery": { zh: "递送", ipa: "/dɪˈlɪvəri/", pos: "n.", ex: "Free delivery is available for orders over fifty.", syn: ["shipment", "dispatch"] },
  "demand": { zh: "要求；需求", ipa: "/dɪˈmɑːnd/", pos: "n./v.", ex: "The demand for electric cars is growing.", syn: ["request", "requirement"] },
  "democracy": { zh: "民主", ipa: "/dɪˈmɒkrəsi/", pos: "n.", ex: "Democracy gives people the right to vote.", syn: ["republic", "self-government"] },
  "democratic": { zh: "民主的", ipa: "/ˌdeməˈkrætɪk/", pos: "adj.", ex: "The country held democratic elections.", syn: ["representative", "popular"] },
  "demonstrate": { zh: "证明；示范", ipa: "/ˈdemənstreɪt/", pos: "v.", ex: "The experiment demonstrates the theory.", syn: ["show", "prove"] },
  "deny": { zh: "否认", ipa: "/dɪˈnaɪ/", pos: "v.", ex: "He denied any involvement in the crime.", syn: ["reject", "refuse"] },
  "department": { zh: "部门", ipa: "/dɪˈpɑːrtmənt/", pos: "n.", ex: "She works in the marketing department.", syn: ["division", "section"] },
  "depend": { zh: "依赖", ipa: "/dɪˈpend/", pos: "v.", ex: "Success depends on hard work.", syn: ["rely", "count on"] },
  "dependent": { zh: "依赖的", ipa: "/dɪˈpendənt/", pos: "adj.", ex: "The child is still dependent on his parents.", syn: ["reliant", "subordinate"] },
  "deploy": { zh: "部署", ipa: "/dɪˈplɔɪ/", pos: "v.", ex: "The army deployed troops to the region.", syn: ["position", "station"] },
  "depression": { zh: "抑郁；萧条", ipa: "/dɪˈpreʃən/", pos: "n.", ex: "She is being treated for depression.", syn: ["sadness", "recession"] },
  "deprive": { zh: "剥夺", ipa: "/dɪˈpraɪv/", pos: "v.", ex: "No one should be deprived of education.", syn: ["strip", "deny"] },
  "derive": { zh: "源于", ipa: "/dɪˈraɪv/", pos: "v.", ex: "The word derives from Latin.", syn: ["originate", "stem"] },
  "describe": { zh: "描述", ipa: "/dɪˈskraɪb/", pos: "v.", ex: "Can you describe what happened?", syn: ["explain", "depict"] },
  "described": { zh: "描述了", ipa: "/dɪˈskraɪbd/", pos: "v.", ex: "She described the scene in detail.", syn: ["explained", "depicted"] },
  "description": { zh: "描述", ipa: "/dɪˈskrɪpʃən/", pos: "n.", ex: "Write a brief description of the product.", syn: ["account", "portrayal"] },
  "deserve": { zh: "值得", ipa: "/dɪˈzɜːrv/", pos: "v.", ex: "You deserve a reward for your efforts.", syn: ["merit", "earn"] },
  "design": { zh: "设计", ipa: "/dɪˈzaɪn/", pos: "n./v.", ex: "The design of the building is modern.", syn: ["plan", "create"] },
  "designed": { zh: "设计了的", ipa: "/dɪˈzaɪnd/", pos: "v.", ex: "The app was designed for students.", syn: ["created", "planned"] },
  "desire": { zh: "渴望", ipa: "/dɪˈzaɪər/", pos: "n./v.", ex: "She has a strong desire to succeed.", syn: ["wish", "want"] },
  "desperate": { zh: "绝望的", ipa: "/ˈdespərət/", pos: "adj.", ex: "He was desperate for a job.", syn: ["hopeless", "frantic"] },
  "despite": { zh: "尽管", ipa: "/dɪˈspaɪt/", pos: "prep.", ex: "Despite the rain, the event continued.", syn: ["regardless of", "in spite of"] },
  "destination": { zh: "目的地", ipa: "/ˌdestɪˈneɪʃən/", pos: "n.", ex: "Paris is a popular tourist destination.", syn: ["goal", "endpoint"] },
  "destroy": { zh: "破坏", ipa: "/dɪˈstrɔɪ/", pos: "v.", ex: "The fire destroyed the entire building.", syn: ["ruin", "demolish"] },
  "destruction": { zh: "破坏", ipa: "/dɪˈstrʌkʃən/", pos: "n.", ex: "The destruction caused by the war was immense.", syn: ["devastation", "ruin"] },
  "detail": { zh: "细节", ipa: "/ˈdiːteɪl/", pos: "n.", ex: "Pay attention to every detail.", syn: ["particular", "specifics"] },
  "detailed": { zh: "详细的", ipa: "/ˈdiːteɪld/", pos: "adj.", ex: "She gave a detailed explanation.", syn: ["thorough", "comprehensive"] },
  "detect": { zh: "检测", ipa: "/dɪˈtekt/", pos: "v.", ex: "The sensor can detect movement.", syn: ["discover", "identify"] },
  "determine": { zh: "确定", ipa: "/dɪˈtɜːrmɪn/", pos: "v.", ex: "We need to determine the cause.", syn: ["decide", "establish"] },
  "determined": { zh: "坚定的", ipa: "/dɪˈtɜːrmɪnd/", pos: "adj.", ex: "She is determined to succeed.", syn: ["resolute", "firm"] },
  "device": { zh: "设备", ipa: "/dɪˈvaɪs/", pos: "n.", ex: "This electronic device is very useful.", syn: ["gadget", "apparatus"] },
  "devote": { zh: "奉献", ipa: "/dɪˈvəʊt/", pos: "v.", ex: "He devoted his life to charity.", syn: ["dedicate", "commit"] },
  "digital": { zh: "数字的", ipa: "/ˈdɪdʒɪtəl/", pos: "adj.", ex: "We live in a digital age.", syn: ["electronic", "computerized"] },
  "dignity": { zh: "尊严", ipa: "/ˈdɪɡnəti/", pos: "n.", ex: "Everyone deserves to be treated with dignity.", syn: ["honor", "self-respect"] },
  "dimension": { zh: "维度", ipa: "/dɪˈmenʃən/", pos: "n.", ex: "The problem has many dimensions.", syn: ["aspect", "scope"] },
  "diminish": { zh: "减少", ipa: "/dɪˈmɪnɪʃ/", pos: "v.", ex: "The pain will diminish over time.", syn: ["decrease", "reduce"] },
  "direct": { zh: "直接的", ipa: "/dɪˈrekt/", pos: "adj./v.", ex: "She gave a direct answer to the question.", syn: ["straightforward", "guide"] },
  "direction": { zh: "方向", ipa: "/dɪˈrekʃən/", pos: "n.", ex: "We are moving in the right direction.", syn: ["way", "course"] },
  "directly": { zh: "直接地", ipa: "/dɪˈrektli/", pos: "adv.", ex: "Contact the manager directly.", syn: ["immediately", "straight"] },
  "director": { zh: "导演；主管", ipa: "/dɪˈrektər/", pos: "n.", ex: "The director approved the plan.", syn: ["manager", "head"] },
  "disappear": { zh: "消失", ipa: "/ˌdɪsəˈpɪər/", pos: "v.", ex: "The sun disappeared behind the clouds.", syn: ["vanish", "fade"] },
  "disappointed": { zh: "失望的", ipa: "/ˌdɪsəˈpɔɪntɪd/", pos: "adj.", ex: "She was disappointed with the results.", syn: ["let down", "unhappy"] },
  "disaster": { zh: "灾难", ipa: "/dɪˈzɑːstər/", pos: "n.", ex: "The earthquake was a major disaster.", syn: ["catastrophe", "calamity"] },
  "discipline": { zh: "纪律", ipa: "/ˈdɪsɪplɪn/", pos: "n.", ex: "Self-discipline is important for success.", syn: ["control", "order"] },
  "disclose": { zh: "透露", ipa: "/dɪsˈkləʊz/", pos: "v.", ex: "The company refused to disclose the information.", syn: ["reveal", "expose"] },
  "discount": { zh: "折扣", ipa: "/ˈdɪskaʊnt/", pos: "n.", ex: "Students get a ten percent discount.", syn: ["reduction", "deal"] },
  "discover": { zh: "发现", ipa: "/dɪˈskʌvər/", pos: "v.", ex: "Scientists discovered a new species.", syn: ["find", "uncover"] },
  "discovered": { zh: "发现了", ipa: "/dɪˈskʌvərd/", pos: "v.", ex: "They discovered the ruins last year.", syn: ["found", "uncovered"] },
  "discovery": { zh: "发现", ipa: "/dɪˈskʌvəri/", pos: "n.", ex: "The discovery changed our understanding.", syn: ["finding", "breakthrough"] },
  "discrimination": { zh: "歧视", ipa: "/dɪˌskrɪmɪˈneɪʃən/", pos: "n.", ex: "Racial discrimination is against the law.", syn: ["prejudice", "bias"] },
  "discuss": { zh: "讨论", ipa: "/dɪˈskʌs/", pos: "v.", ex: "We need to discuss the matter.", syn: ["talk about", "debate"] },
  "discussed": { zh: "讨论了", ipa: "/dɪˈskʌst/", pos: "v.", ex: "They discussed the plan in detail.", syn: ["debated", "talked about"] },
  "discussion": { zh: "讨论", ipa: "/dɪˈskʌʃən/", pos: "n.", ex: "We had a productive discussion.", syn: ["conversation", "dialogue"] },
  "disease": { zh: "疾病", ipa: "/dɪˈziːz/", pos: "n.", ex: "Heart disease is a leading cause of death.", syn: ["illness", "sickness"] },
  "dismiss": { zh: "解雇；驳回", ipa: "/dɪsˈmɪs/", pos: "v.", ex: "The judge dismissed the case.", syn: ["reject", "fire"] },
  "disorder": { zh: "混乱；疾病", ipa: "/dɪsˈɔːrdər/", pos: "n.", ex: "The room was in complete disorder.", syn: ["chaos", "confusion"] },
  "display": { zh: "展示", ipa: "/dɪˈspleɪ/", pos: "v./n.", ex: "The museum displays ancient artifacts.", syn: ["show", "exhibit"] },
  "dispute": { zh: "争论", ipa: "/dɪˈspjuːt/", pos: "n./v.", ex: "The border dispute lasted for years.", syn: ["conflict", "disagreement"] },
  "distance": { zh: "距离", ipa: "/ˈdɪstəns/", pos: "n.", ex: "The distance between the two cities is short.", syn: ["length", "range"] },
  "distinct": { zh: "明显的", ipa: "/dɪˈstɪŋkt/", pos: "adj.", ex: "There is a distinct difference between the two.", syn: ["clear", "definite"] },
  "distinction": { zh: "区别", ipa: "/dɪˈstɪŋkʃən/", pos: "n.", ex: "We must make a distinction between fact and opinion.", syn: ["difference", "variation"] },
  "distinguish": { zh: "区分", ipa: "/dɪˈstɪŋɡwɪʃ/", pos: "v.", ex: "Can you distinguish between the two colors?", syn: ["differentiate", "tell apart"] },
  "distribute": { zh: "分配", ipa: "/dɪˈstrɪbjuːt/", pos: "v.", ex: "The teacher distributed the worksheets.", syn: ["hand out", "allocate"] },
  "distribution": { zh: "分配", ipa: "/ˌdɪstrɪˈbjuːʃən/", pos: "n.", ex: "The distribution of wealth is unequal.", syn: ["allocation", "dispersal"] },
  "district": { zh: "区", ipa: "/ˈdɪstrɪkt/", pos: "n.", ex: "She lives in the business district.", syn: ["area", "region"] },
  "diverse": { zh: "多样的", ipa: "/daɪˈvɜːrs/", pos: "adj.", ex: "The school has a diverse student body.", syn: ["varied", "assorted"] },
  "diversity": { zh: "多样性", ipa: "/daɪˈvɜːrsəti/", pos: "n.", ex: "Cultural diversity enriches society.", syn: ["variety", "range"] },
  "divide": { zh: "分开", ipa: "/dɪˈvaɪd/", pos: "v.", ex: "Divide the cake into equal pieces.", syn: ["split", "separate"] },
  "document": { zh: "文件", ipa: "/ˈdɒkjumənt/", pos: "n.", ex: "Please sign the document.", syn: ["paper", "record"] },
  "domain": { zh: "领域", ipa: "/dəˈmeɪn/", pos: "n.", ex: "Mathematics is her domain of expertise.", syn: ["field", "area"] },
  "domestic": { zh: "国内的", ipa: "/dəˈmestɪk/", pos: "adj.", ex: "Domestic flights are cheaper.", syn: ["internal", "home"] },
  "dominant": { zh: "占主导的", ipa: "/ˈdɒmɪnənt/", pos: "adj.", ex: "English is the dominant language in business.", syn: ["leading", "prevailing"] },
  "dominate": { zh: "支配", ipa: "/ˈdɒmɪneɪt/", pos: "v.", ex: "A few companies dominate the market.", syn: ["control", "rule"] },
  "donate": { zh: "捐赠", ipa: "/dəʊˈneɪt/", pos: "v.", ex: "She donated blood at the hospital.", syn: ["give", "contribute"] },
  "donation": { zh: "捐赠", ipa: "/dəʊˈneɪʃən/", pos: "n.", ex: "The charity received a generous donation.", syn: ["gift", "contribution"] },
  "door": { zh: "门", ipa: "/dɔːr/", pos: "n.", ex: "Please close the door when you leave.", syn: ["entrance", "gate"] },
  "doubt": { zh: "怀疑", ipa: "/daʊt/", pos: "n./v.", ex: "I have no doubt about his ability.", syn: ["uncertainty", "question"] },
  "downtown": { zh: "市中心", ipa: "/ˌdaʊnˈtaʊn/", pos: "n./adv.", ex: "The office is located downtown.", syn: ["city center", "urban area"] },
  "draft": { zh: "草案", ipa: "/drɑːft/", pos: "n.", ex: "She wrote the first draft of her novel.", syn: ["outline", "sketch"] },
  "drag": { zh: "拖拉", ipa: "/dræɡ/", pos: "v.", ex: "He dragged the heavy box across the floor.", syn: ["pull", "haul"] },
  "drama": { zh: "戏剧", ipa: "/ˈdrɑːmə/", pos: "n.", ex: "She studied drama at university.", syn: ["play", "theater"] },
  "dramatic": { zh: "戏剧性的", ipa: "/drəˈmætɪk/", pos: "adj.", ex: "There has been a dramatic improvement.", syn: ["striking", "impressive"] },
  "dramatically": { zh: "戏剧性地", ipa: "/drəˈmætɪkli/", pos: "adv.", ex: "The situation changed dramatically.", syn: ["significantly", "remarkably"] },
  "draw": { zh: "画；吸引", ipa: "/drɔː/", pos: "v.", ex: "She can draw very well.", syn: ["sketch", "attract"] },
  "drawn": { zh: "画的", ipa: "/drɔːn/", pos: "v.", ex: "The curtains were drawn shut.", syn: ["pulled", "attracted"] },
  "dream": { zh: "梦想", ipa: "/driːm/", pos: "n./v.", ex: "Her dream is to travel the world.", syn: ["ambition", "aspiration"] },
  "dress": { zh: "穿衣", ipa: "/dres/", pos: "v./n.", ex: "She wore a beautiful red dress.", syn: ["clothing", "outfit"] },
  "drift": { zh: "漂流", ipa: "/drɪft/", pos: "v./n.", ex: "The boat began to drift downstream.", syn: ["float", "wander"] },
  "drink": { zh: "饮料；喝", ipa: "/drɪŋk/", pos: "n./v.", ex: "Would you like something to drink?", syn: ["beverage", "sip"] },
  "drive": { zh: "驾驶；驱动", ipa: "/draɪv/", pos: "v./n.", ex: "She learned to drive last year.", syn: ["operate", "steer"] },
  "driven": { zh: "被驱动的", ipa: "/ˈdrɪvən/", pos: "adj.", ex: "He is a driven and ambitious person.", syn: ["motivated", "determined"] },
  "drop": { zh: "落下；下降", ipa: "/drɒp/", pos: "v./n.", ex: "Temperatures will drop tonight.", syn: ["fall", "decrease"] },
  "dropped": { zh: "下降了", ipa: "/drɒpt/", pos: "v.", ex: "He dropped his phone on the floor.", syn: ["fell", "declined"] },
  "drug": { zh: "药物", ipa: "/drʌɡ/", pos: "n.", ex: "The new drug is very effective.", syn: ["medicine", "medication"] },
  "dry": { zh: "干的", ipa: "/draɪ/", pos: "adj.", ex: "The weather has been very dry this summer.", syn: ["arid", "parched"] },
  "due": { zh: "由于；到期的", ipa: "/djuː/", pos: "adj.", ex: "The report is due next Monday.", syn: ["expected", "owed"] },
  "dull": { zh: "沉闷的", ipa: "/dʌl/", pos: "adj.", ex: "The lecture was long and dull.", syn: ["boring", "tedious"] },
  "duration": { zh: "持续时间", ipa: "/djʊˈreɪʃən/", pos: "n.", ex: "The duration of the flight is three hours.", syn: ["length", "period"] },
  "duty": { zh: "责任", ipa: "/ˈdjuːti/", pos: "n.", ex: "It is our duty to protect the environment.", syn: ["responsibility", "obligation"] },
  "dynamic": { zh: "动态的", ipa: "/daɪˈnæmɪk/", pos: "adj.", ex: "The market is very dynamic.", syn: ["energetic", "active"] },
};

// For words not in our dictionary, generate a reasonable entry
function generateEntry(word, id) {
  const entry = DICT[word];
  if (entry) {
    return {
      id: `extra_${id}`,
      word: word,
      chinese: entry.zh,
      ipa: entry.ipa,
      partOfSpeech: entry.pos,
      exampleSentence: entry.ex,
      synonyms: entry.syn || []
    };
  }
  
  // For words not in dictionary, create a basic entry
  return {
    id: `extra_${id}`,
    word: word,
    chinese: `[${word}]`,
    ipa: "",
    partOfSpeech: "",
    exampleSentence: "",
    synonyms: []
  };
}

// Generate entries
const extraWords = [];
let id = 1;
let inDict = 0;
let notInDict = 0;

for (const word of missingWords) {
  // Double-check not in CET
  if (cetSet.has(word)) continue;
  
  const entry = generateEntry(word, id);
  if (DICT[word]) {
    inDict++;
  } else {
    notInDict++;
  }
  extraWords.push(entry);
  id++;
}

console.log(`Total extra words generated: ${extraWords.length}`);
console.log(`In dictionary: ${inDict}`);
console.log(`Not in dictionary (need filling): ${notInDict}`);

// Write the output
fs.writeFileSync(
  path.join(__dirname, '../src/data/extra_words.json'),
  JSON.stringify(extraWords, null, 2)
);

// Also write the list of words that still need dictionary entries
const needDict = extraWords.filter(w => w.chinese.startsWith('[')).map(w => w.word);
fs.writeFileSync(
  path.join(__dirname, 'needs_dictionary.json'),
  JSON.stringify(needDict, null, 2)
);
console.log(`\nWords still needing dictionary entries: ${needDict.length}`);
if (needDict.length > 0) {
  console.log('Sample:', needDict.slice(0, 30).join(', '));
}
